CeladonCity_Condominiums_Roof_MapScripts::
	.byte 0

CeladonCity_Condominiums_Roof_EventScript_Sign::
	msgbox CeladonCity_Condominiums_Roof_Text_Sign, MSGBOX_SIGN
	end

CeladonCity_Condominiums_Roof_EventScript_Sign_2::
	msgbox CeladonCity_Condominiums_Roof_Text_Sign_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_Roof_Text_Sign:
	.string "I KNOW EVERYTHING!$"

CeladonCity_Condominiums_Roof_Text_Sign_2:
	.string "I KNOW EVERYTHING!$"
