GoldenrodDeptStore5F_MapScripts::
	.byte 0

GoldenrodDeptStore5F_EventScript_Clerk::
	msgbox GoldenrodDeptStore5F_Text_Clerk, MSGBOX_NPC
	end

GoldenrodDeptStore5F_EventScript_Lass::
	msgbox GoldenrodDeptStore5F_Text_Lass, MSGBOX_NPC
	end

GoldenrodDeptStore5F_EventScript_Mike::
	msgbox GoldenrodDeptStore5F_Text_Mike, MSGBOX_NPC
	end

GoldenrodDeptStore5F_EventScript_PokefanM::
	msgbox GoldenrodDeptStore5F_Text_PokefanM, MSGBOX_NPC
	end

GoldenrodDeptStore5F_EventScript_Carrie::
	msgbox GoldenrodDeptStore5F_Text_Carrie, MSGBOX_NPC
	end

GoldenrodDeptStore5F_EventScript_Directory::
	msgbox GoldenrodDeptStore5F_Text_Directory, MSGBOX_SIGN
	end

GoldenrodDeptStore5F_Text_Clerk:
	.string "Word is a strong trainer crossed\nthe sea from HOENN. I wonder if\lthey'll pass through JOHTO too.$"

GoldenrodDeptStore5F_Text_Lass:
	.string "On Sundays, a lady\ncomes to check out\lPOKéMON.\pShe even gives\naway TMs!$"

GoldenrodDeptStore5F_Text_Mike:
	.string "This route sure gets more foot\ntraffic now that HOENN trainers\lkeep showing up.$"

GoldenrodDeptStore5F_Text_PokefanM:
	.string "You can't rename a\nPOKéMON you get in\la trade.\pThe name is a re-\nflection of the\poriginal trainer's\nfeelings for it.$"

GoldenrodDeptStore5F_Text_Carrie:
	.string "JOHTO's changed a lot since the\nHOENN champion opened the sea\lroutes here.$"

GoldenrodDeptStore5F_Text_Directory:
	.string "Customize Your\nPOKéMON\p5F TM CORNER$"
