SSAnne_2F_Room5_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_Gentleman, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_LittleBoy, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_Gentleman:
	.string "Have you gone to the SAFARI ZONE\nin FUCHSIA CITY?\pThere are many kinds of rare\nPOKéMON.$"

SSAnne_2F_Room5_Text_LittleBoy:
	.string "Me and my daddy think the SAFARI\nZONE is awesome!\lI wish we could go there again.$"
