FuchsiaCity_WardensHouse_MapScripts::
	.byte 0

FuchsiaCity_WardensHouse_EventScript_Warden::
	msgbox FuchsiaCity_WardensHouse_Text_Warden, MSGBOX_NPC
	end

FuchsiaCity_WardensHouse_EventScript_DisplaySign2::
	msgbox FuchsiaCity_WardensHouse_Text_DisplaySign2, MSGBOX_SIGN
	end

FuchsiaCity_WardensHouse_EventScript_DisplaySign1::
	msgbox FuchsiaCity_WardensHouse_Text_DisplaySign1, MSGBOX_SIGN
	end

FuchsiaCity_WardensHouse_EventScript_DisplaySign1_2::
	msgbox FuchsiaCity_WardensHouse_Text_DisplaySign1_2, MSGBOX_SIGN
	end

FuchsiaCity_WardensHouse_EventScript_DisplaySign2_2::
	msgbox FuchsiaCity_WardensHouse_Text_DisplaySign2_2, MSGBOX_SIGN
	end

FuchsiaCity_WardensHouse_Text_Warden:
	.string "The name's BAOBA, if you want to\nget official about it. Folks 'round\lhere just call me the WARDEN.\pLost my GOLD TEETH out in the ZONE\nsomewhere. Can't whistle right\lwithout 'em -- but I get by.\pNever met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"

FuchsiaCity_WardensHouse_Text_DisplaySign2:
	.string "Old POKéMON merchandise is on\ndisplay.$"

FuchsiaCity_WardensHouse_Text_DisplaySign1:
	.string "POKéMON photos and fossils are on\ndisplay.$"

FuchsiaCity_WardensHouse_Text_DisplaySign1_2:
	.string "POKéMON photos and fossils are on\ndisplay.$"

FuchsiaCity_WardensHouse_Text_DisplaySign2_2:
	.string "Old POKéMON merchandise is on\ndisplay.$"
