RockTunnel_B1F_MapScripts::
	.byte 0

RockTunnel_B1F_EventScript_Cooper::
	trainerbattle_single TRAINER_KANTO_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperSeen, RockTunnel_B1F_Text_CooperBeaten
	msgbox RockTunnel_B1F_Text_CooperBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Dudley::
	trainerbattle_single TRAINER_KANTO_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleySeen, RockTunnel_B1F_Text_DudleyBeaten
	msgbox RockTunnel_B1F_Text_DudleyBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Sofia::
	trainerbattle_single TRAINER_KANTO_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaSeen, RockTunnel_B1F_Text_SofiaBeaten
	msgbox RockTunnel_B1F_Text_SofiaBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Allen::
	trainerbattle_single TRAINER_KANTO_HIKER_ALLEN, RockTunnel_B1F_Text_AllenSeen, RockTunnel_B1F_Text_AllenBeaten
	msgbox RockTunnel_B1F_Text_AllenBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Eric::
	trainerbattle_single TRAINER_KANTO_HIKER_ERIC, RockTunnel_B1F_Text_EricSeen, RockTunnel_B1F_Text_EricBeaten
	msgbox RockTunnel_B1F_Text_EricBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Steve::
	trainerbattle_single TRAINER_KANTO_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveSeen, RockTunnel_B1F_Text_SteveBeaten
	msgbox RockTunnel_B1F_Text_SteveBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Martha::
	trainerbattle_single TRAINER_KANTO_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaSeen, RockTunnel_B1F_Text_MarthaBeaten
	msgbox RockTunnel_B1F_Text_MarthaBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_Winston::
	trainerbattle_single TRAINER_KANTO_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonSeen, RockTunnel_B1F_Text_WinstonBeaten
	msgbox RockTunnel_B1F_Text_WinstonBeaten, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_Text_CooperSeen:
	.string "…$"

RockTunnel_B1F_Text_CooperBeaten:
	.string "…$"

RockTunnel_B1F_Text_DudleySeen:
	.string "…$"

RockTunnel_B1F_Text_DudleyBeaten:
	.string "…$"

RockTunnel_B1F_Text_SofiaSeen:
	.string "…$"

RockTunnel_B1F_Text_SofiaBeaten:
	.string "…$"

RockTunnel_B1F_Text_AllenSeen:
	.string "…$"

RockTunnel_B1F_Text_AllenBeaten:
	.string "…$"

RockTunnel_B1F_Text_EricSeen:
	.string "…$"

RockTunnel_B1F_Text_EricBeaten:
	.string "…$"

RockTunnel_B1F_Text_SteveSeen:
	.string "…$"

RockTunnel_B1F_Text_SteveBeaten:
	.string "…$"

RockTunnel_B1F_Text_MarthaSeen:
	.string "…$"

RockTunnel_B1F_Text_MarthaBeaten:
	.string "…$"

RockTunnel_B1F_Text_WinstonSeen:
	.string "…$"

RockTunnel_B1F_Text_WinstonBeaten:
	.string "…$"
