CeladonCity_Condominiums_1F_MapScripts::
	.byte 0

CeladonCity_Condominiums_1F_EventScript_TeaWoman::
	msgbox CeladonCity_Condominiums_1F_Text_TeaWoman, MSGBOX_NPC
	end

CeladonCity_Condominiums_1F_EventScript_SuiteSign::
	msgbox CeladonCity_Condominiums_1F_Text_SuiteSign, MSGBOX_SIGN
	end

CeladonCity_Condominiums_1F_EventScript_SuiteSign_2::
	msgbox CeladonCity_Condominiums_1F_Text_SuiteSign_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_1F_Text_TeaWoman:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeladonCity_Condominiums_1F_Text_SuiteSign:
	.string "CELADON MANSION\nManager's Suite$"

CeladonCity_Condominiums_1F_Text_SuiteSign_2:
	.string "CELADON MANSION\nManager's Suite$"
