Route16_NorthEntrance_2F_MapScripts::
	.byte 0

Route16_NorthEntrance_2F_EventScript_LittleBoy::
	msgbox Route16_NorthEntrance_2F_Text_LittleBoy, MSGBOX_NPC
	end

Route16_NorthEntrance_2F_EventScript_LittleGirl::
	msgbox Route16_NorthEntrance_2F_Text_LittleGirl, MSGBOX_NPC
	end

Route16_NorthEntrance_2F_EventScript_Aide::
	msgbox Route16_NorthEntrance_2F_Text_Aide, MSGBOX_NPC
	end

Route16_NorthEntrance_2F_EventScript_LeftBinoculars::
	msgbox Route16_NorthEntrance_2F_Text_LeftBinoculars, MSGBOX_SIGN
	end

Route16_NorthEntrance_2F_EventScript_RightBinoculars::
	msgbox Route16_NorthEntrance_2F_Text_RightBinoculars, MSGBOX_SIGN
	end

Route16_NorthEntrance_2F_Text_LittleBoy:
	.string "I'm on a relaxing ride on my new\nbike with my girlfriend.$"

Route16_NorthEntrance_2F_Text_LittleGirl:
	.string "We're going riding together on our\nnew bikes.$"

Route16_NorthEntrance_2F_Text_Aide:
	.string "PROF. OAK's aides stopped handing\nthings out. Too many trainers\lnow -- and one of them is you.$"

Route16_NorthEntrance_2F_Text_LeftBinoculars:
	.string "Let's see what the binoculars have\nto show…\pIt's the CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_RightBinoculars:
	.string "Let's see what the binoculars have\nto show…\pThere's a long path over water far\naway.$"
