FuchsiaCity_MapScripts::
	.byte 0

FuchsiaCity_EventScript_Erik::
	msgbox FuchsiaCity_Text_Erik, MSGBOX_NPC
	end

FuchsiaCity_EventScript_Youngster::
	msgbox FuchsiaCity_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_EventScript_LittleBoy::
	msgbox FuchsiaCity_Text_LittleBoy, MSGBOX_NPC
	end

FuchsiaCity_EventScript_OldMan::
	msgbox FuchsiaCity_Text_OldMan, MSGBOX_NPC
	end

FuchsiaCity_EventScript_Lass::
	msgbox FuchsiaCity_Text_Lass, MSGBOX_NPC
	end

FuchsiaCity_EventScript_CitySign::
	msgbox FuchsiaCity_Text_CitySign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariZoneSign::
	msgbox FuchsiaCity_Text_SafariZoneSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_GymSign::
	msgbox FuchsiaCity_Text_GymSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_WardensHomeSign::
	msgbox FuchsiaCity_Text_WardensHomeSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_VoltorbSign::
	msgbox FuchsiaCity_Text_VoltorbSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SlowpokeSign::
	msgbox FuchsiaCity_Text_SlowpokeSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_ChanseySign::
	msgbox FuchsiaCity_Text_ChanseySign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_KangaskhanSign::
	msgbox FuchsiaCity_Text_KangaskhanSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_FossilMonSign::
	msgbox FuchsiaCity_Text_FossilMonSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_LaprasSign::
	msgbox FuchsiaCity_Text_LaprasSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariGameSign::
	msgbox FuchsiaCity_Text_SafariGameSign, MSGBOX_SIGN
	end

FuchsiaCity_Text_Erik:
	.string "ERIK: Where's SARA?\nI said I'd meet her here.$"

FuchsiaCity_Text_Youngster:
	.string "That item ball in there…\nWere you wanting that?\pMe, too!\n…Huh? That's a POKéMON?$"

FuchsiaCity_Text_LittleBoy:
	.string "Did you try the SAFARI GAME?\pThere are some rare POKéMON that\ncan only be caught there.$"

FuchsiaCity_Text_OldMan:
	.string "The SAFARI ZONE has a zoo in front\nof the entrance.\pOut back is the SAFARI GAME for\ncatching POKéMON.$"

FuchsiaCity_Text_Lass:
	.string "The LEADER here is JANINE.\nShe won't see you sooner for\lbeing famous.$"

FuchsiaCity_Text_CitySign:
	.string "FUCHSIA CITY\nBehold! It's Passion Pink!$"

FuchsiaCity_Text_SafariZoneSign:
	.string "POKéMON PARADISE\nSAFARI ZONE$"

FuchsiaCity_Text_GymSign:
	.string "FUCHSIA CITY POKéMON GYM\nLEADER: JANINE\lThe Poisonous Ninja Master$"

FuchsiaCity_Text_WardensHomeSign:
	.string "SAFARI ZONE\nWARDEN'S HOME$"

FuchsiaCity_Text_VoltorbSign:
	.string "Name: VOLTORB\nThe very image of a POKé BALL.$"

FuchsiaCity_Text_SlowpokeSign:
	.string "Name: SLOWPOKE\nFriendly and very slow moving.$"

FuchsiaCity_Text_ChanseySign:
	.string "Name: CHANSEY\nCatching one is all up to chance.$"

FuchsiaCity_Text_KangaskhanSign:
	.string "Name: KANGASKHAN\pA maternal POKéMON that raises its\nyoung in a pouch on its belly.$"

FuchsiaCity_Text_FossilMonSign:
	.string "Name: KABUTO\nAn extremely rare POKéMON that was\lregenerated from a fossil.$"

FuchsiaCity_Text_LaprasSign:
	.string "Name: LAPRAS\nAKA the king of the seas.$"

FuchsiaCity_Text_SafariGameSign:
	.string "SAFARI GAME\nPOKéMON-U-CATCH!$"
