RuinsOfAlphKabutoItemRoom_MapScripts::
	.byte 0

RuinsOfAlphKabutoItemRoom_EventScript_AncientReplica::
	msgbox RuinsOfAlphKabutoItemRoom_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphKabutoItemRoom_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphKabutoItemRoom_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphKabutoItemRoom_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphKabutoItemRoom_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
