RuinsOfAlphOmanyteChamber_MapScripts::
	.byte 0

RuinsOfAlphOmanyteChamber_EventScript_AncientReplica::
	msgbox RuinsOfAlphOmanyteChamber_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphOmanyteChamber_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphOmanyteChamber_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphOmanyteChamber_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphOmanyteChamber_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
