VermilionCity_PokemonFanClub_MapScripts::
	.byte 0

VermilionCity_PokemonFanClub_EventScript_Chairman::
	msgbox VermilionCity_PokemonFanClub_Text_Chairman, MSGBOX_NPC
	end

VermilionCity_PokemonFanClub_EventScript_WorkerF::
	msgbox VermilionCity_PokemonFanClub_Text_WorkerF, MSGBOX_NPC
	end

VermilionCity_PokemonFanClub_EventScript_Pikachu::
	msgbox VermilionCity_PokemonFanClub_Text_Pikachu, MSGBOX_NPC
	end

VermilionCity_PokemonFanClub_EventScript_Woman::
	msgbox VermilionCity_PokemonFanClub_Text_Woman, MSGBOX_NPC
	end

VermilionCity_PokemonFanClub_EventScript_FatMan::
	msgbox VermilionCity_PokemonFanClub_Text_FatMan, MSGBOX_NPC
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign1::
	msgbox VermilionCity_PokemonFanClub_Text_RulesSign1, MSGBOX_SIGN
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign2::
	msgbox VermilionCity_PokemonFanClub_Text_RulesSign2, MSGBOX_SIGN
	end

VermilionCity_PokemonFanClub_Text_Chairman:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

VermilionCity_PokemonFanClub_Text_WorkerF:
	.string "Our CHAIRMAN is very vocal about\nPOKéMON.$"

VermilionCity_PokemonFanClub_Text_Pikachu:
	.string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Woman:
	.string "I just adore my SEEL!\nIt's so lovable!\pIt squeals, “Kyuuuh,” when I\nhug it!$"

VermilionCity_PokemonFanClub_Text_FatMan:
	.string "Won't you admire my PIKACHU's\nadorable tail?$"

VermilionCity_PokemonFanClub_Text_RulesSign1:
	.string "Let's all listen politely to other\nTRAINERS!$"

VermilionCity_PokemonFanClub_Text_RulesSign2:
	.string "If someone brags, brag right back!$"
