FuchsiaCity_House1_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_OldMan::
	msgbox FuchsiaCity_House1_Text_OldMan, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Woman::
	msgbox FuchsiaCity_House1_Text_Woman, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_LittleBoy::
	msgbox FuchsiaCity_House1_Text_LittleBoy, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_OldMan:
	.string "I've fished this stretch of KANTO\nfor years. Lately it's all anyone\ltalks about -- some far-off champion.$"

FuchsiaCity_House1_Text_Woman:
	.string "The SAFARI ZONE's WARDEN is old, \nbut he's still very much active.\pAll his teeth are false, though.$"

FuchsiaCity_House1_Text_LittleBoy:
	.string "BILL files his own POKéMON data on\nhis PC.\pDid he show you?$"
