FuchsiaCity_House1_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_OldMan::
	msgbox FuchsiaCity_House1_Text_OldMan, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Woman::
	msgbox FuchsiaCity_House1_Text_Woman, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_LittleBoy::
	msgbox FuchsiaCity_House1_Text_LittleBoy, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_OldMan:
	.string "Hmm?\nYou've met BILL?\pHe's my grandson!\pHe always liked collecting things,\neven as a child!$"

FuchsiaCity_House1_Text_Woman:
	.string "The SAFARI ZONE's WARDEN is old, \nbut he's still very much active.\pAll his teeth are false, though.$"

FuchsiaCity_House1_Text_LittleBoy:
	.string "BILL files his own POKéMON data on\nhis PC.\pDid he show you?$"
