CinnabarIsland_PokemonLab_Lounge_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_Lounge_EventScript_Scientist::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Scientist, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Clifton, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_EventScript_Norma::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Norma, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_Text_Scientist:
	.string "I found this most remarkable fossil\ninside MT. MOON.\pI think it's of a rare, prehistoric\nPOKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_Clifton:
	.string "I traded away the one I wanted,\nyears back. Still think on it.$"

CinnabarIsland_PokemonLab_Lounge_Text_Norma:
	.string "I had a trade lined up. The other\nhalf never came back to KANTO.$"
