CinnabarIsland_PokemonLab_Lounge_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_Lounge_EventScript_Scientist::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Scientist, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Clifton, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_EventScript_Norma::
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_Norma, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_Lounge_Text_Scientist:
	.string "I found this most remarkable fossil\ninside MT. MOON.\pI think it's of a rare, prehistoric\nPOKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_Clifton:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

CinnabarIsland_PokemonLab_Lounge_Text_Norma:
	.string "Never met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"
