SaffronCity_CopycatsHouse_1F_MapScripts::
	.byte 0

SaffronCity_CopycatsHouse_1F_EventScript_CopycatsDad::
	msgbox SaffronCity_CopycatsHouse_1F_Text_CopycatsDad, MSGBOX_NPC
	end

SaffronCity_CopycatsHouse_1F_EventScript_CopycatsMom::
	msgbox SaffronCity_CopycatsHouse_1F_Text_CopycatsMom, MSGBOX_NPC
	end

SaffronCity_CopycatsHouse_1F_Text_CopycatsDad:
	.string "My daughter likes to mimic people.\nIt's rather vexing.\pHer mimicry has earned her the\nnickname COPYCAT around here.$"

SaffronCity_CopycatsHouse_1F_Text_CopycatsMom:
	.string "My daughter is so self-centered.\nShe has but a few friends.$"
