KurtsHouse_MapScripts::
	.byte 0

KurtsHouse_EventScript_OakPhoto::
	msgbox KurtsHouse_Text_OakPhoto, MSGBOX_SIGN
	end

KurtsHouse_EventScript_OakPhoto_2::
	msgbox KurtsHouse_Text_OakPhoto_2, MSGBOX_SIGN
	end

KurtsHouse_EventScript_CelebiStatue::
	msgbox KurtsHouse_Text_CelebiStatue, MSGBOX_SIGN
	end

KurtsHouse_Text_OakPhoto:
	.string "…A young PROF.\nOAK?$"

KurtsHouse_Text_OakPhoto_2:
	.string "…A young PROF.\nOAK?$"

KurtsHouse_Text_CelebiStatue:
	.string "It's a statue of\nthe forest's pro-\ltector.$"
