PewterCity_Museum_1F_MapScripts::
	.byte 0

PewterCity_Museum_1F_EventScript_Scientist1::
	msgbox PewterCity_Museum_1F_Text_Scientist1, MSGBOX_NPC
	end

PewterCity_Museum_1F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_OldMan, MSGBOX_NPC
	end

PewterCity_Museum_1F_EventScript_OldAmberScientist::
	msgbox PewterCity_Museum_1F_Text_OldAmberScientist, MSGBOX_NPC
	end

PewterCity_Museum_1F_EventScript_OldAmber::
	msgbox PewterCity_Museum_1F_Text_OldAmber, MSGBOX_NPC
	end

PewterCity_Museum_1F_EventScript_Scientist2::
	msgbox PewterCity_Museum_1F_Text_Scientist2, MSGBOX_NPC
	end

PewterCity_Museum_1F_EventScript_AerodactylFossil::
	msgbox PewterCity_Museum_1F_Text_AerodactylFossil, MSGBOX_SIGN
	end

PewterCity_Museum_1F_EventScript_KabutopsFossil::
	msgbox PewterCity_Museum_1F_Text_KabutopsFossil, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_Scientist1:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

PewterCity_Museum_1F_Text_OldMan:
	.string "I should be grateful for my long\nlife.\pNever did I think I would get to\nsee the bones of a dragon!$"

PewterCity_Museum_1F_Text_OldAmberScientist:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

PewterCity_Museum_1F_Text_OldAmber:
	.string "There is a beautiful piece of\nAMBER in a clear gold color.$"

PewterCity_Museum_1F_Text_Scientist2:
	.string "We have two fossils of rare,\nprehistoric POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_AerodactylFossil:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

PewterCity_Museum_1F_Text_KabutopsFossil:
	.string "This route's seen more foot traffic\nlately. Something about a champion\lpassing through from JOHTO.$"
