CianwoodCity_MapScripts::
	.byte 0

CianwoodCity_EventScript_Youngster::
	msgbox CianwoodCity_Text_Youngster, MSGBOX_NPC
	end

CianwoodCity_EventScript_PokefanM::
	msgbox CianwoodCity_Text_PokefanM, MSGBOX_NPC
	end

CianwoodCity_EventScript_Lass::
	msgbox CianwoodCity_Text_Lass, MSGBOX_NPC
	end

CianwoodCity_EventScript_ChucksWife::
	msgbox CianwoodCity_Text_ChucksWife, MSGBOX_NPC
	end

CianwoodCity_EventScript_Sign::
	msgbox CianwoodCity_Text_Sign, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CianwoodGymSign::
	msgbox CianwoodCity_Text_CianwoodGymSign, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CianwoodPharmacySign::
	msgbox CianwoodCity_Text_CianwoodPharmacySign, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CianwoodPhotoStudioSign::
	msgbox CianwoodCity_Text_CianwoodPhotoStudioSign, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CianwoodPokeSeerSign::
	msgbox CianwoodCity_Text_CianwoodPokeSeerSign, MSGBOX_SIGN
	end

CianwoodCity_Text_Youngster:
	.string "If you use FLY,\nyou can get back\pto OLIVINE in-\nstantly.$"

CianwoodCity_Text_PokefanM:
	.string "Boulders to the\nnorth of town can\lbe crushed.\pThey may be hiding\nsomething.\pYour POKéMON could\nuse ROCK SMASH to\lbreak them.$"

CianwoodCity_Text_Lass:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"

CianwoodCity_Text_ChucksWife:
	.string "They say the HOENN champion's\njourney is just getting started.\lWonder where they'll go next.$"

CianwoodCity_Text_Sign:
	.string "CIANWOOD CITY\pA Port Surrounded\nby Rough Seas$"

CianwoodCity_Text_CianwoodGymSign:
	.string "CIANWOOD CITY\nPOKéMON GYM\pLEADER: CHUCK\pHis Roaring Fists\nDo the Talking$"

CianwoodCity_Text_CianwoodPharmacySign:
	.string "500 Years of\nTradition\pCIANWOOD CITY\nPHARMACY\pWe Await Your\nMedicinal Queries$"

CianwoodCity_Text_CianwoodPhotoStudioSign:
	.string "CIANWOOD CITY\nPHOTO STUDIO\pTake a Snapshot as\na Keepsake!$"

CianwoodCity_Text_CianwoodPokeSeerSign:
	.string "THE POKé SEER\nAHEAD$"
