PlayersNeighborsHouse_MapScripts::
	.byte 0

PlayersNeighborsHouse_EventScript_PlayersNeighborsDaughter::
	msgbox PlayersNeighborsHouse_Text_PlayersNeighborsDaughter, MSGBOX_NPC
	end

PlayersNeighborsHouse_Text_PlayersNeighborsDaughter:
	.string "PIKACHU is an\nevolved POKéMON.\pI was amazed by\nPROF.ELM's find-\lings.\pHe's so famous for\nhis research on\lPOKéMON evolution.\p…sigh…\pI wish I could be\na researcher like\lhim…$"
