PewterCity_Museum_2F_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_2F_Text_Scientist, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_2F_Text_Man, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_2F_Text_OldMan, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_2F_Text_LittleGirl, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_2F_Text_BaldingMan, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_2F_Text_MoonStone, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle_2::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle_2, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle_3::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle_3, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle_4::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle_4, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle_5::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle_5, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle_6::
	msgbox PewterCity_Museum_2F_Text_SpaceShuttle_6, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone_2::
	msgbox PewterCity_Museum_2F_Text_MoonStone_2, MSGBOX_SIGN
	end

PewterCity_Museum_2F_Text_Scientist:
	.string "This month, we're running a space\nexhibit.$"

PewterCity_Museum_2F_Text_Man:
	.string "MOON STONE, huh?\pWhat's so special about it?\nLooks like an ordinary rock to me.$"

PewterCity_Museum_2F_Text_OldMan:
	.string "July 20, 1969!\pHumankind first set foot on the\nmoon that day.\pI bought a color TV just so I\ncould watch that news.$"

PewterCity_Museum_2F_Text_LittleGirl:
	.string "I want a PIKACHU!\nIt's so cute!\pI asked my daddy to catch me one!$"

PewterCity_Museum_2F_Text_BaldingMan:
	.string "Yeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_2F_Text_MoonStone:
	.string "A meteorite that fell on MT. MOON.\nIt is thought to be a MOON STONE.$"

PewterCity_Museum_2F_Text_SpaceShuttle:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_SpaceShuttle_2:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_SpaceShuttle_3:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_SpaceShuttle_4:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_SpaceShuttle_5:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_SpaceShuttle_6:
	.string "Space Shuttle$"

PewterCity_Museum_2F_Text_MoonStone_2:
	.string "A meteorite that fell on MT. MOON.\nIt is thought to be a MOON STONE.$"
