Route19_MapScripts::
	.byte 0

Route19_EventScript_Reece::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_REECE, Route19_Text_ReeceSeen, Route19_Text_ReeceBeaten
	msgbox Route19_Text_ReeceBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Richard::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_RICHARD, Route19_Text_RichardSeen, Route19_Text_RichardBeaten
	msgbox Route19_Text_RichardBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Tony::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_TONY, Route19_Text_TonySeen, Route19_Text_TonyBeaten
	msgbox Route19_Text_TonyBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Matthew::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_MATTHEW, Route19_Text_MatthewSeen, Route19_Text_MatthewBeaten
	msgbox Route19_Text_MatthewBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Douglas::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_DOUGLAS, Route19_Text_DouglasSeen, Route19_Text_DouglasBeaten
	msgbox Route19_Text_DouglasBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_David::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_DAVID, Route19_Text_DavidSeen, Route19_Text_DavidBeaten
	msgbox Route19_Text_DavidBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Axle::
	trainerbattle_single TRAINER_KANTO_SWIMMER_M_AXLE, Route19_Text_AxleSeen, Route19_Text_AxleBeaten
	msgbox Route19_Text_AxleBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Alice::
	trainerbattle_single TRAINER_KANTO_SWIMMER_F_ALICE, Route19_Text_AliceSeen, Route19_Text_AliceBeaten
	msgbox Route19_Text_AliceBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Connie::
	trainerbattle_single TRAINER_KANTO_SWIMMER_F_CONNIE, Route19_Text_ConnieSeen, Route19_Text_ConnieBeaten
	msgbox Route19_Text_ConnieBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Anya::
	trainerbattle_single TRAINER_KANTO_SWIMMER_F_ANYA, Route19_Text_AnyaSeen, Route19_Text_AnyaBeaten
	msgbox Route19_Text_AnyaBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Lia::
	trainerbattle_single TRAINER_KANTO_SIS_AND_BRO_LIA_LUC, Route19_Text_LiaSeen, Route19_Text_LiaBeaten
	msgbox Route19_Text_LiaBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_Luc::
	trainerbattle_single TRAINER_KANTO_SIS_AND_BRO_LIA_LUC_2, Route19_Text_LucSeen, Route19_Text_LucBeaten
	msgbox Route19_Text_LucBeaten, MSGBOX_AUTOCLOSE
	end

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_ReeceSeen:
	.string "…$"

Route19_Text_ReeceBeaten:
	.string "…$"

Route19_Text_RichardSeen:
	.string "…$"

Route19_Text_RichardBeaten:
	.string "…$"

Route19_Text_TonySeen:
	.string "…$"

Route19_Text_TonyBeaten:
	.string "…$"

Route19_Text_MatthewSeen:
	.string "…$"

Route19_Text_MatthewBeaten:
	.string "…$"

Route19_Text_DouglasSeen:
	.string "…$"

Route19_Text_DouglasBeaten:
	.string "…$"

Route19_Text_DavidSeen:
	.string "…$"

Route19_Text_DavidBeaten:
	.string "…$"

Route19_Text_AxleSeen:
	.string "…$"

Route19_Text_AxleBeaten:
	.string "…$"

Route19_Text_AliceSeen:
	.string "…$"

Route19_Text_AliceBeaten:
	.string "…$"

Route19_Text_ConnieSeen:
	.string "…$"

Route19_Text_ConnieBeaten:
	.string "…$"

Route19_Text_AnyaSeen:
	.string "…$"

Route19_Text_AnyaBeaten:
	.string "…$"

Route19_Text_LiaSeen:
	.string "…$"

Route19_Text_LiaBeaten:
	.string "…$"

Route19_Text_LucSeen:
	.string "…$"

Route19_Text_LucBeaten:
	.string "…$"

Route19_Text_RouteSign:
	.string "SEA ROUTE 19\nFUCHSIA CITY - SEAFOAM ISLANDS$"
