CeruleanCity_House5_MapScripts::
	.byte 0

CeruleanCity_House5_EventScript_BerryPowderMan::
	msgbox CeruleanCity_House5_Text_BerryPowderMan, MSGBOX_NPC
	end

CeruleanCity_House5_EventScript_BerryCrushRankings::
	msgbox CeruleanCity_House5_Text_BerryCrushRankings, MSGBOX_SIGN
	end

CeruleanCity_House5_Text_BerryPowderMan:
	.string "I grind BERRIES into powder.\nQuiet work. I'd like it to\lstay quiet.$"

CeruleanCity_House5_Text_BerryCrushRankings:
	.string "A rankings board for BERRY\nCRUSH. Every line is blank.$"
