CeruleanCity_House5_MapScripts::
	.byte 0

CeruleanCity_House5_EventScript_BerryPowderMan::
	msgbox CeruleanCity_House5_Text_BerryPowderMan, MSGBOX_NPC
	end

CeruleanCity_House5_EventScript_BerryCrushRankings::
	msgbox CeruleanCity_House5_Text_BerryCrushRankings, MSGBOX_SIGN
	end

CeruleanCity_House5_Text_BerryPowderMan:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

CeruleanCity_House5_Text_BerryCrushRankings:
	.string "I've fished this stretch of KANTO\nfor years. Lately it's all anyone\ltalks about -- some far-off champion.$"
