Route2_ViridianForest_NorthEntrance_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_Youngster, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_OldMan, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CooltrainerF, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_Youngster:
	.string "Many POKéMON live only in forests \nand caves.\pYou need to be persistent and look\neverywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_OldMan:
	.string "Have you noticed the skinny trees\non the roadside?\pThey can be cut down by a special\nPOKéMON move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CooltrainerF:
	.string "Do you know the evolution-cancel\ntechnique?\pWhen a POKéMON is evolving, you\ncan stop the process.\pIt's a technique for raising\nPOKéMON the way they are.$"
