CianwoodPokecenter1F_MapScripts::
	.byte 0

CianwoodPokecenter1F_EventScript_Nurse::
	msgbox CianwoodPokecenter1F_Text_Nurse, MSGBOX_NPC
	end

CianwoodPokecenter1F_EventScript_Lass::
	msgbox CianwoodPokecenter1F_Text_Lass, MSGBOX_NPC
	end

CianwoodPokecenter1F_EventScript_CianwoodGymGuide::
	msgbox CianwoodPokecenter1F_Text_CianwoodGymGuide, MSGBOX_NPC
	end

CianwoodPokecenter1F_EventScript_SuperNerd::
	msgbox CianwoodPokecenter1F_Text_SuperNerd, MSGBOX_NPC
	end

CianwoodPokecenter1F_Text_Nurse:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"

CianwoodPokecenter1F_Text_Lass:
	.string "Did you meet the\nPOKéMANIAC?\pHe's always brag-\nging about his\lrare POKéMON.$"

CianwoodPokecenter1F_Text_CianwoodGymGuide:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

CianwoodPokecenter1F_Text_SuperNerd:
	.string "I love showing off\nthe POKéMON that\pI've raised.\nDon't you?\pI'm going to get\ninto a bunch of\pbattles, and show\noff my POKéMON!$"
