SSAnne_Kitchen_MapScripts::
	.byte 0

SSAnne_Kitchen_EventScript_Chef1::
	msgbox SSAnne_Kitchen_Text_Chef1, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef2::
	msgbox SSAnne_Kitchen_Text_Chef2, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef3::
	msgbox SSAnne_Kitchen_Text_Chef3, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef4::
	msgbox SSAnne_Kitchen_Text_Chef4, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef5::
	msgbox SSAnne_Kitchen_Text_Chef5, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef6::
	msgbox SSAnne_Kitchen_Text_Chef6, MSGBOX_NPC
	end

SSAnne_Kitchen_EventScript_Chef7::
	msgbox SSAnne_Kitchen_Text_Chef7, MSGBOX_NPC
	end

SSAnne_Kitchen_Text_Chef1:
	.string "You, mon petit!\nWe're busy here!\lOut of the way!$"

SSAnne_Kitchen_Text_Chef2:
	.string "I saw an odd BERRY in the trash.\nI wonder what that was?$"

SSAnne_Kitchen_Text_Chef3:
	.string "I'm so busy I'm getting dizzy!\nYou have to give me room here!$"

SSAnne_Kitchen_Text_Chef4:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

SSAnne_Kitchen_Text_Chef5:
	.string "Hum-de-hum-de-ho…\pI peel spuds every day!\nHum-hum…$"

SSAnne_Kitchen_Text_Chef6:
	.string "Did you hear about SNORLAX?\nIt's a glutton.\pNo other POKéMON eats and sleeps\nthe way SNORLAX can and does!$"

SSAnne_Kitchen_Text_Chef7:
	.string "Snivel… Sniff…\pI only get to peel onions…\nSnivel…$"
