VioletKylesHouse_MapScripts::
	.byte 0

VioletKylesHouse_EventScript_PokefanM::
	msgbox VioletKylesHouse_Text_PokefanM, MSGBOX_NPC
	end

VioletKylesHouse_EventScript_Kyle::
	msgbox VioletKylesHouse_Text_Kyle, MSGBOX_NPC
	end

VioletKylesHouse_Text_PokefanM:
	.string "A POKéMON you get\nin a trade grows\lquickly.\pBut if you don't\nhave the right GYM\pBADGE, they may\ndisobey you.$"

VioletKylesHouse_Text_Kyle:
	.string "They say the HOENN champion's\njourney is just getting started.\lWonder where they'll go next.$"
