GoldenrodDeptStoreB1F_MapScripts::
	.byte 0

GoldenrodDeptStoreB1F_EventScript_BlackBelt1::
	msgbox GoldenrodDeptStoreB1F_Text_BlackBelt1, MSGBOX_NPC
	end

GoldenrodDeptStoreB1F_EventScript_BlackBelt2::
	msgbox GoldenrodDeptStoreB1F_Text_BlackBelt2, MSGBOX_NPC
	end

GoldenrodDeptStoreB1F_EventScript_BlackBelt3::
	msgbox GoldenrodDeptStoreB1F_Text_BlackBelt3, MSGBOX_NPC
	end

GoldenrodDeptStoreB1F_Text_BlackBelt1:
	.string "Hey, kid! You're\nholding us up!\pOur policy is to\nwork behind the\pscenes where no\none can see us!$"

GoldenrodDeptStoreB1F_Text_BlackBelt2:
	.string "I lose my passion\nfor work if some-\lone's watching.\pCome on, kid,\nscoot!$"

GoldenrodDeptStoreB1F_Text_BlackBelt3:
	.string "Oohah! Oohah!\pThe stuff on the\nground's junk.\pTake it if you\nwant it!$"
