VioletPokecenter1F_MapScripts::
	.byte 0

VioletPokecenter1F_EventScript_VioletPokecenterNurse::
	msgbox VioletPokecenter1F_Text_VioletPokecenterNurse, MSGBOX_NPC
	end

VioletPokecenter1F_EventScript_Gentleman::
	msgbox VioletPokecenter1F_Text_Gentleman, MSGBOX_NPC
	end

VioletPokecenter1F_EventScript_Youngster::
	msgbox VioletPokecenter1F_Text_Youngster, MSGBOX_NPC
	end

VioletPokecenter1F_Text_VioletPokecenterNurse:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

VioletPokecenter1F_Text_Gentleman:
	.string "It was around\nthree years ago.\pTEAM ROCKET was up\nto no good with\lPOKéMON.\pBut justice pre-\nvailed--a young\lkid broke 'em up.$"

VioletPokecenter1F_Text_Youngster:
	.string "POKéMON are smart.\nThey won't obey a\ptrainer they don't\nrespect.\pWithout the right\nGYM BADGES, they\pwill just do as\nthey please.$"
