CinnabarIsland_PokemonLab_ResearchRoom_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_MetronomeTutor::
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_MetronomeTutor, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Scientist::
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_Scientist, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_AmberPipe::
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_AmberPipe, MSGBOX_SIGN
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Computer::
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_Computer, MSGBOX_SIGN
	end

CinnabarIsland_PokemonLab_ResearchRoom_Text_MetronomeTutor:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_Scientist:
	.string "EEVEE can evolve into one of three\nkinds of POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AmberPipe:
	.string "An amber pipe!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_Computer:
	.string "There's an e-mail message.\p… … …\pThere are three legendary bird\nPOKéMON.\pThey are ARTICUNO, ZAPDOS, and\nMOLTRES.\pTheir whereabouts are unknown.\pWe plan to explore the cavern\nclose to CERULEAN.\pFrom: POKéMON RESEARCH TEAM…$"
