PalletTown_RivalsHouse_MapScripts::
	.byte 0

PalletTown_RivalsHouse_EventScript_Bookshelf::
	msgbox PalletTown_RivalsHouse_Text_Bookshelf, MSGBOX_SIGN
	end

PalletTown_RivalsHouse_EventScript_Bookshelf_2::
	msgbox PalletTown_RivalsHouse_Text_Bookshelf_2, MSGBOX_SIGN
	end

PalletTown_RivalsHouse_EventScript_Picture::
	msgbox PalletTown_RivalsHouse_Text_Picture, MSGBOX_SIGN
	end

PalletTown_RivalsHouse_Text_Bookshelf:
	.string "The shelves are crammed full of\nbooks on POKéMON.$"

PalletTown_RivalsHouse_Text_Bookshelf_2:
	.string "The shelves are crammed full of\nbooks on POKéMON.$"

PalletTown_RivalsHouse_Text_Picture:
	.string "“The lovely and sweet\nCLEFAIRY”$"
