SilverCavePokecenter1F_MapScripts::
	.byte 0

SilverCavePokecenter1F_EventScript_Nurse::
	msgbox SilverCavePokecenter1F_Text_Nurse, MSGBOX_NPC
	end

SilverCavePokecenter1F_EventScript_Granny::
	msgbox SilverCavePokecenter1F_Text_Granny, MSGBOX_NPC
	end

SilverCavePokecenter1F_Text_Nurse:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

SilverCavePokecenter1F_Text_Granny:
	.string "Trainers who seek\npower climb MT.\pSILVER despite its\nmany dangers…\pWith their trusted\nPOKéMON, they must\pfeel they can go\nanywhere…$"
