KantoSafariZone_North_MapScripts::
	.byte 0

KantoSafariZone_North_EventScript_TrainerTips1::
	msgbox KantoSafariZone_North_Text_TrainerTips1, MSGBOX_SIGN
	end

KantoSafariZone_North_EventScript_AreaSign::
	msgbox KantoSafariZone_North_Text_AreaSign, MSGBOX_SIGN
	end

KantoSafariZone_North_EventScript_TrainerTips2::
	msgbox KantoSafariZone_North_Text_TrainerTips2, MSGBOX_SIGN
	end

KantoSafariZone_North_EventScript_TrainerTips3::
	msgbox KantoSafariZone_North_Text_TrainerTips3, MSGBOX_SIGN
	end

KantoSafariZone_North_EventScript_RestHouseSign::
	msgbox KantoSafariZone_North_Text_RestHouseSign, MSGBOX_SIGN
	end

KantoSafariZone_North_Text_TrainerTips1:
	.string "TRAINER TIPS\pThe SECRET HOUSE is still ahead.$"

KantoSafariZone_North_Text_AreaSign:
	.string "AREA 2$"

KantoSafariZone_North_Text_TrainerTips2:
	.string "TRAINER TIPS\pPOKéMON hide in tall grass.\pZigzag through grassy areas to\nflush them out.$"

KantoSafariZone_North_Text_TrainerTips3:
	.string "TRAINER TIPS\pFind the SECRET HOUSE for a nice\nsurprise.$"

KantoSafariZone_North_Text_RestHouseSign:
	.string "REST HOUSE$"
