CeladonCity_DepartmentStore_2F_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_2F_EventScript_Lass::
	msgbox CeladonCity_DepartmentStore_2F_Text_Lass, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_2F_EventScript_ClerkItems::
	msgbox CeladonCity_DepartmentStore_2F_Text_ClerkItems, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_2F_EventScript_ClerkTMs::
	msgbox CeladonCity_DepartmentStore_2F_Text_ClerkTMs, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_2F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_2F_Text_FloorSign, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_2F_Text_Lass:
	.string "For long outings, you should buy\nREVIVE.$"

CeladonCity_DepartmentStore_2F_Text_ClerkItems:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

CeladonCity_DepartmentStore_2F_Text_ClerkTMs:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign:
	.string "Top-Grade Items for TRAINERS!\p2F: TRAINER'S MARKET$"
