Route39Farmhouse_MapScripts::
	.byte 0

Route39Farmhouse_EventScript_PokefanM_DairyFarmer::
	msgbox Route39Farmhouse_Text_PokefanM_DairyFarmer, MSGBOX_NPC
	end

Route39Farmhouse_EventScript_PokefanF_SnoreFarmer::
	msgbox Route39Farmhouse_Text_PokefanF_SnoreFarmer, MSGBOX_NPC
	end

Route39Farmhouse_Text_PokefanM_DairyFarmer:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

Route39Farmhouse_Text_PokefanF_SnoreFarmer:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"
