Route2_EastBuilding_MapScripts::
	.byte 0

Route2_EastBuilding_EventScript_Aide::
	msgbox Route2_EastBuilding_Text_Aide, MSGBOX_NPC
	end

Route2_EastBuilding_EventScript_Rocker::
	msgbox Route2_EastBuilding_Text_Rocker, MSGBOX_NPC
	end

Route2_EastBuilding_Text_Aide:
	.string "PROF. OAK's aides stopped handing\nthings out. Too many trainers\lnow -- and one of them is you.$"

Route2_EastBuilding_Text_Rocker:
	.string "Once a POKéMON learns FLASH, you\ncan get through ROCK TUNNEL.$"
