Route2_EastBuilding_MapScripts::
	.byte 0

Route2_EastBuilding_EventScript_Aide::
	msgbox Route2_EastBuilding_Text_Aide, MSGBOX_NPC
	end

Route2_EastBuilding_EventScript_Rocker::
	msgbox Route2_EastBuilding_Text_Rocker, MSGBOX_NPC
	end

Route2_EastBuilding_Text_Aide:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

Route2_EastBuilding_Text_Rocker:
	.string "Once a POKéMON learns FLASH, you\ncan get through ROCK TUNNEL.$"
