Route36RuinsOfAlphGate_MapScripts::
	.byte 0

Route36RuinsOfAlphGate_EventScript_Officer::
	msgbox Route36RuinsOfAlphGate_Text_Officer, MSGBOX_NPC
	end

Route36RuinsOfAlphGate_EventScript_Gramps::
	msgbox Route36RuinsOfAlphGate_Text_Gramps, MSGBOX_NPC
	end

Route36RuinsOfAlphGate_Text_Officer:
	.string "Don't you wonder\nwho'd make some-\lthing like this?\lAnd why?$"

Route36RuinsOfAlphGate_Text_Gramps:
	.string "Did you see that\nstrange tree in\lthe road?\pThat may explain\nwhy fewer people\pare visiting the\nRUINS OF ALPH.$"
