GoldenrodBikeShop_MapScripts::
	.byte 0

GoldenrodBikeShop_EventScript_Clerk::
	msgbox GoldenrodBikeShop_Text_Clerk, MSGBOX_NPC
	end

GoldenrodBikeShop_EventScript_Bicycle::
	msgbox GoldenrodBikeShop_Text_Bicycle, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_2::
	msgbox GoldenrodBikeShop_Text_Bicycle_2, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_3::
	msgbox GoldenrodBikeShop_Text_Bicycle_3, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_4::
	msgbox GoldenrodBikeShop_Text_Bicycle_4, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_5::
	msgbox GoldenrodBikeShop_Text_Bicycle_5, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_6::
	msgbox GoldenrodBikeShop_Text_Bicycle_6, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_7::
	msgbox GoldenrodBikeShop_Text_Bicycle_7, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_8::
	msgbox GoldenrodBikeShop_Text_Bicycle_8, MSGBOX_SIGN
	end

GoldenrodBikeShop_EventScript_Bicycle_9::
	msgbox GoldenrodBikeShop_Text_Bicycle_9, MSGBOX_SIGN
	end

GoldenrodBikeShop_Text_Clerk:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

GoldenrodBikeShop_Text_Bicycle:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_2:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_3:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_4:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_5:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_6:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_7:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_8:
	.string "It's a shiny new\nBICYCLE!$"

GoldenrodBikeShop_Text_Bicycle_9:
	.string "It's a shiny new\nBICYCLE!$"
