BlackthornPokecenter1F_MapScripts::
	.byte 0

BlackthornPokecenter1F_EventScript_Nurse::
	msgbox BlackthornPokecenter1F_Text_Nurse, MSGBOX_NPC
	end

BlackthornPokecenter1F_EventScript_Gentleman::
	msgbox BlackthornPokecenter1F_Text_Gentleman, MSGBOX_NPC
	end

BlackthornPokecenter1F_EventScript_Twin::
	msgbox BlackthornPokecenter1F_Text_Twin, MSGBOX_NPC
	end

BlackthornPokecenter1F_EventScript_CooltrainerM::
	msgbox BlackthornPokecenter1F_Text_CooltrainerM, MSGBOX_NPC
	end

BlackthornPokecenter1F_Text_Nurse:
	.string "I've lived in JOHTO my whole life.\nNever thought I'd meet someone\lfrom HOENN way out here.$"

BlackthornPokecenter1F_Text_Gentleman:
	.string "Deep inside far-\noff INDIGO PLATEAU\pis the POKéMON\nLEAGUE.\pI hear the best\ntrainers gather\pthere from around\nthe country.$"

BlackthornPokecenter1F_Text_Twin:
	.string "There was this\nmove I just had\pto teach my POKé-\nMON.\pSo I got the MOVE\nDELETER to make it\lforget an HM move.$"

BlackthornPokecenter1F_Text_CooltrainerM:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"
