CeladonCity_Condominiums_3F_MapScripts::
	.byte 0

CeladonCity_Condominiums_3F_EventScript_Programmer::
	msgbox CeladonCity_Condominiums_3F_Text_Programmer, MSGBOX_NPC
	end

CeladonCity_Condominiums_3F_EventScript_Designer::
	msgbox CeladonCity_Condominiums_3F_Text_Designer, MSGBOX_NPC
	end

CeladonCity_Condominiums_3F_EventScript_GraphicArtist::
	msgbox CeladonCity_Condominiums_3F_Text_GraphicArtist, MSGBOX_NPC
	end

CeladonCity_Condominiums_3F_EventScript_Writer::
	msgbox CeladonCity_Condominiums_3F_Text_Writer, MSGBOX_NPC
	end

CeladonCity_Condominiums_3F_EventScript_DevelopmentRoomSign::
	msgbox CeladonCity_Condominiums_3F_Text_DevelopmentRoomSign, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer1::
	msgbox CeladonCity_Condominiums_3F_Text_Computer1, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer2::
	msgbox CeladonCity_Condominiums_3F_Text_Computer2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer3::
	msgbox CeladonCity_Condominiums_3F_Text_Computer3, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_DevelopmentRoomSign_2::
	msgbox CeladonCity_Condominiums_3F_Text_DevelopmentRoomSign_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer3_2::
	msgbox CeladonCity_Condominiums_3F_Text_Computer3_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer1_2::
	msgbox CeladonCity_Condominiums_3F_Text_Computer1_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_EventScript_Computer2_2::
	msgbox CeladonCity_Condominiums_3F_Text_Computer2_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_3F_Text_Programmer:
	.string "Me?\nI'm the programmer!$"

CeladonCity_Condominiums_3F_Text_Designer:
	.string "Is that right?\pI'm the game designer!\pFilling up your POKéDEX is tough,\nbut don't quit!\pWhen you finish, come tell me!$"

CeladonCity_Condominiums_3F_Text_GraphicArtist:
	.string "I'm the graphic artist!\nI drew you!$"

CeladonCity_Condominiums_3F_Text_Writer:
	.string "I wrote the story!\nIsn't ERIKA cute?\pI like MISTY a lot, too!\nOh, and SABRINA, I like her!$"

CeladonCity_Condominiums_3F_Text_DevelopmentRoomSign:
	.string "GAME FREAK Development Room$"

CeladonCity_Condominiums_3F_Text_Computer1:
	.string "It's the game program! Messing with\nit could bug out the game!$"

CeladonCity_Condominiums_3F_Text_Computer2:
	.string "Someone's playing a game instead of\nworking!$"

CeladonCity_Condominiums_3F_Text_Computer3:
	.string "It's the script!\nBetter not look at the ending!$"

CeladonCity_Condominiums_3F_Text_DevelopmentRoomSign_2:
	.string "GAME FREAK Development Room$"

CeladonCity_Condominiums_3F_Text_Computer3_2:
	.string "It's the script!\nBetter not look at the ending!$"

CeladonCity_Condominiums_3F_Text_Computer1_2:
	.string "It's the game program! Messing with\nit could bug out the game!$"

CeladonCity_Condominiums_3F_Text_Computer2_2:
	.string "Someone's playing a game instead of\nworking!$"
