VioletCity_MapScripts::
	.byte 0

VioletCity_EventScript_Lass::
	msgbox VioletCity_Text_Lass, MSGBOX_NPC
	end

VioletCity_EventScript_SuperNerd::
	msgbox VioletCity_Text_SuperNerd, MSGBOX_NPC
	end

VioletCity_EventScript_Gramps::
	msgbox VioletCity_Text_Gramps, MSGBOX_NPC
	end

VioletCity_EventScript_Youngster::
	msgbox VioletCity_Text_Youngster, MSGBOX_NPC
	end

VioletCity_EventScript_Sign::
	msgbox VioletCity_Text_Sign, MSGBOX_SIGN
	end

VioletCity_EventScript_VioletGymSign::
	msgbox VioletCity_Text_VioletGymSign, MSGBOX_SIGN
	end

VioletCity_EventScript_SproutTowerSign::
	msgbox VioletCity_Text_SproutTowerSign, MSGBOX_SIGN
	end

VioletCity_EventScript_EarlsPokemonAcademySign::
	msgbox VioletCity_Text_EarlsPokemonAcademySign, MSGBOX_SIGN
	end

VioletCity_Text_Lass:
	.string "Ghosts are rumored\nto appear in\lSPROUT TOWER.\pThey said normal-\ntype POKéMON moves\phad no effect on\nghosts.$"

VioletCity_Text_SuperNerd:
	.string "Hey, you're a\nPOKéMON trainer?\pIf you beat the\nGYM LEADER here,\pyou'll be ready\nfor prime time!$"

VioletCity_Text_Gramps:
	.string "FALKNER, from the\nVIOLET POKéMON\pGYM, is a fine\ntrainer!\pHe inherited his\nfather's gym and\phas done a great\njob with it.$"

VioletCity_Text_Youngster:
	.string "I saw a wiggly\ntree up ahead!\pIf you touch it,\nit squirms and\ldances! Cool!$"

VioletCity_Text_Sign:
	.string "VIOLET CITY\pThe City of\nNostalgic Scents$"

VioletCity_Text_VioletGymSign:
	.string "VIOLET CITY\nPOKéMON GYM\lLEADER: FALKNER\pThe Elegant Master\nof Flying POKéMON$"

VioletCity_Text_SproutTowerSign:
	.string "SPROUT TOWER\pExperience the\nWay of POKéMON$"

VioletCity_Text_EarlsPokemonAcademySign:
	.string "EARL'S POKéMON\nACADEMY$"
