ViridianCity_Gym_MapScripts::
	.byte 0

ViridianCity_Gym_EventScript_Takashi::
	trainerbattle_single TRAINER_KANTO_BLACK_BELT_TAKASHI, ViridianCity_Gym_Text_TakashiSeen, ViridianCity_Gym_Text_TakashiBeaten
	msgbox ViridianCity_Gym_Text_TakashiBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Yuji::
	trainerbattle_single TRAINER_KANTO_COOLTRAINER_YUJI, ViridianCity_Gym_Text_YujiSeen, ViridianCity_Gym_Text_YujiBeaten
	msgbox ViridianCity_Gym_Text_YujiBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Atsushi::
	trainerbattle_single TRAINER_KANTO_BLACK_BELT_ATSUSHI, ViridianCity_Gym_Text_AtsushiSeen, ViridianCity_Gym_Text_AtsushiBeaten
	msgbox ViridianCity_Gym_Text_AtsushiBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Jason::
	trainerbattle_single TRAINER_KANTO_TAMER_JASON, ViridianCity_Gym_Text_JasonSeen, ViridianCity_Gym_Text_JasonBeaten
	msgbox ViridianCity_Gym_Text_JasonBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Cole::
	trainerbattle_single TRAINER_KANTO_TAMER_COLE, ViridianCity_Gym_Text_ColeSeen, ViridianCity_Gym_Text_ColeBeaten
	msgbox ViridianCity_Gym_Text_ColeBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Kiyo::
	trainerbattle_single TRAINER_KANTO_BLACK_BELT_KIYO, ViridianCity_Gym_Text_KiyoSeen, ViridianCity_Gym_Text_KiyoBeaten
	msgbox ViridianCity_Gym_Text_KiyoBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Samuel::
	trainerbattle_single TRAINER_KANTO_COOLTRAINER_SAMUEL, ViridianCity_Gym_Text_SamuelSeen, ViridianCity_Gym_Text_SamuelBeaten
	msgbox ViridianCity_Gym_Text_SamuelBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_Warren::
	trainerbattle_single TRAINER_KANTO_COOLTRAINER_WARREN, ViridianCity_Gym_Text_WarrenSeen, ViridianCity_Gym_Text_WarrenBeaten
	msgbox ViridianCity_Gym_Text_WarrenBeaten, MSGBOX_AUTOCLOSE
	end

ViridianCity_Gym_EventScript_GymGuy::
	msgbox ViridianCity_Gym_Text_GymGuy, MSGBOX_NPC
	end

ViridianCity_Gym_EventScript_GymStatue::
	msgbox ViridianCity_Gym_Text_GymStatue, MSGBOX_SIGN
	end

ViridianCity_Gym_EventScript_GymStatue_2::
	msgbox ViridianCity_Gym_Text_GymStatue_2, MSGBOX_SIGN
	end

ViridianCity_Gym_Text_TakashiSeen:
	.string "…$"

ViridianCity_Gym_Text_TakashiBeaten:
	.string "…$"

ViridianCity_Gym_Text_YujiSeen:
	.string "…$"

ViridianCity_Gym_Text_YujiBeaten:
	.string "…$"

ViridianCity_Gym_Text_AtsushiSeen:
	.string "…$"

ViridianCity_Gym_Text_AtsushiBeaten:
	.string "…$"

ViridianCity_Gym_Text_JasonSeen:
	.string "…$"

ViridianCity_Gym_Text_JasonBeaten:
	.string "…$"

ViridianCity_Gym_Text_ColeSeen:
	.string "…$"

ViridianCity_Gym_Text_ColeBeaten:
	.string "…$"

ViridianCity_Gym_Text_KiyoSeen:
	.string "…$"

ViridianCity_Gym_Text_KiyoBeaten:
	.string "…$"

ViridianCity_Gym_Text_SamuelSeen:
	.string "…$"

ViridianCity_Gym_Text_SamuelBeaten:
	.string "…$"

ViridianCity_Gym_Text_WarrenSeen:
	.string "…$"

ViridianCity_Gym_Text_WarrenBeaten:
	.string "…$"

ViridianCity_Gym_Text_GymGuy:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

ViridianCity_Gym_Text_GymStatue:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

ViridianCity_Gym_Text_GymStatue_2:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"
