OlivinePokecenter1F_MapScripts::
	.byte 0

OlivinePokecenter1F_EventScript_Nurse::
	msgbox OlivinePokecenter1F_Text_Nurse, MSGBOX_NPC
	end

OlivinePokecenter1F_EventScript_FishingGuru::
	msgbox OlivinePokecenter1F_Text_FishingGuru, MSGBOX_NPC
	end

OlivinePokecenter1F_EventScript_Fisher::
	msgbox OlivinePokecenter1F_Text_Fisher, MSGBOX_NPC
	end

OlivinePokecenter1F_EventScript_Teacher::
	msgbox OlivinePokecenter1F_Text_Teacher, MSGBOX_NPC
	end

OlivinePokecenter1F_Text_Nurse:
	.string "The old timers say JOHTO used to\nfeel far from everywhere. Not\lanymore, with HOENN so close now.$"

OlivinePokecenter1F_Text_FishingGuru:
	.string "The old timers say JOHTO used to\nfeel far from everywhere. Not\lanymore, with HOENN so close now.$"

OlivinePokecenter1F_Text_Fisher:
	.string "The SAILOR in the\nOLIVINE CAFE next\pdoor is really\ngenerous.\pHe taught my\nPOKéMON STRENGTH.\pNow it can move\nbig boulders.$"

OlivinePokecenter1F_Text_Teacher:
	.string "There's a person\nin CIANWOOD CITY\lacross the sea.\pI heard him brag-\nging about his\lrare POKéMON.$"
