EcruteakLugiaSpeechHouse_MapScripts::
	.byte 0

EcruteakLugiaSpeechHouse_EventScript_Gramps::
	msgbox EcruteakLugiaSpeechHouse_Text_Gramps, MSGBOX_NPC
	end

EcruteakLugiaSpeechHouse_EventScript_Youngster::
	msgbox EcruteakLugiaSpeechHouse_Text_Youngster, MSGBOX_NPC
	end

EcruteakLugiaSpeechHouse_Text_Gramps:
	.string "This happened when\nI was young.\pThe sky suddenly\nturned black. A\pgiant flying POKé-\nMON was blocking\lout the sun.\pI wonder what that\nPOKéMON was? \pIt was like a bird\nand a dragon.$"

EcruteakLugiaSpeechHouse_Text_Youngster:
	.string "Is there really a\nPOKéMON that big?\pIf it exists, it\nmust be powerful.$"
