PewterCity_House2_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_OldMan, MSGBOX_NPC
	end

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_LittleBoy, MSGBOX_NPC
	end

PewterCity_House2_Text_OldMan:
	.string "POKéMON learn new techniques as\nthey grow.\pBut some moves must be taught to\nthem by people.$"

PewterCity_House2_Text_LittleBoy:
	.string "A POKéMON becomes easier to \ncatch if it has a status problem.\pSleep, poison, burn, or paralysis…\nThose are all effective.\pBut catching POKéMON is never\na sure thing!$"
