CeladonCity_DepartmentStore_Roof_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_Roof_EventScript_CooltrainerM::
	msgbox CeladonCity_DepartmentStore_Roof_Text_CooltrainerM, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_Roof_EventScript_ThirstyGirl::
	msgbox CeladonCity_DepartmentStore_Roof_Text_ThirstyGirl, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_Roof_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_Roof_Text_FloorSign, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Roof_EventScript_VendingMachine::
	msgbox CeladonCity_DepartmentStore_Roof_Text_VendingMachine, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Roof_EventScript_VendingMachine_2::
	msgbox CeladonCity_DepartmentStore_Roof_Text_VendingMachine_2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Roof_EventScript_VendingMachine_3::
	msgbox CeladonCity_DepartmentStore_Roof_Text_VendingMachine_3, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Roof_Text_CooltrainerM:
	.string "My sister is a TRAINER, believe it\nor not.\pBut, she's so immature, she drives\nme nuts!$"

CeladonCity_DepartmentStore_Roof_Text_ThirstyGirl:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign:
	.string "ROOFTOP SQUARE:\nVENDING MACHINES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachine:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachine_2:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachine_3:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"
