CinnabarIsland_PokemonLab_ExperimentRoom_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_ExperimentRoom_EventScript_Garett::
	msgbox CinnabarIsland_PokemonLab_ExperimentRoom_Text_Garett, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_ExperimentRoom_EventScript_FossilScientist::
	msgbox CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilScientist, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_ExperimentRoom_Text_Garett:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilScientist:
	.string "Never met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"
