RuinsOfAlphHoOhChamber_MapScripts::
	.byte 0

RuinsOfAlphHoOhChamber_EventScript_AncientReplica::
	msgbox RuinsOfAlphHoOhChamber_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphHoOhChamber_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphHoOhChamber_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphHoOhChamber_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphHoOhChamber_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
