CherrygroveEvolutionSpeechHouse_MapScripts::
	.byte 0

CherrygroveEvolutionSpeechHouse_EventScript_Lass::
	msgbox CherrygroveEvolutionSpeechHouse_Text_Lass, MSGBOX_NPC
	end

CherrygroveEvolutionSpeechHouse_EventScript_Youngster::
	msgbox CherrygroveEvolutionSpeechHouse_Text_Youngster, MSGBOX_NPC
	end

CherrygroveEvolutionSpeechHouse_Text_Lass:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

CherrygroveEvolutionSpeechHouse_Text_Youngster:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"
