GoldenrodDeptStore2F_MapScripts::
	.byte 0

GoldenrodDeptStore2F_EventScript_Clerk1::
	msgbox GoldenrodDeptStore2F_Text_Clerk1, MSGBOX_NPC
	end

GoldenrodDeptStore2F_EventScript_Clerk2::
	msgbox GoldenrodDeptStore2F_Text_Clerk2, MSGBOX_NPC
	end

GoldenrodDeptStore2F_EventScript_Youngster::
	msgbox GoldenrodDeptStore2F_Text_Youngster, MSGBOX_NPC
	end

GoldenrodDeptStore2F_EventScript_CooltrainerF::
	msgbox GoldenrodDeptStore2F_Text_CooltrainerF, MSGBOX_NPC
	end

GoldenrodDeptStore2F_EventScript_Gentleman::
	msgbox GoldenrodDeptStore2F_Text_Gentleman, MSGBOX_NPC
	end

GoldenrodDeptStore2F_EventScript_Directory::
	msgbox GoldenrodDeptStore2F_Text_Directory, MSGBOX_SIGN
	end

GoldenrodDeptStore2F_Text_Clerk1:
	.string "Nothing much happens around here,\nbut ever since that ferry started\lrunning to HOENN, who knows.$"

GoldenrodDeptStore2F_Text_Clerk2:
	.string "The old timers say JOHTO used to\nfeel far from everywhere. Not\lanymore, with HOENN so close now.$"

GoldenrodDeptStore2F_Text_Youngster:
	.string "POKéGEAR can store\nup to ten phone\lnumbers.\pIt's hard to de-\ncide which numbers\lto keep.$"

GoldenrodDeptStore2F_Text_CooltrainerF:
	.string "I got my ABRA at\nthe GAME CORNER.\pNow it's my best\npartner.$"

GoldenrodDeptStore2F_Text_Gentleman:
	.string "This DEPT.STORE\nmakes me realize\pthat GOLDENROD is\na big city.\pThe selection here\nis unmatched any-\lwhere else.$"

GoldenrodDeptStore2F_Text_Directory:
	.string "Your Travel\nCompanion\p2F TRAINER'S\n   MARKET$"
