MtEmber_RubyPath_B4F_MapScripts::
	.byte 0

MtEmber_RubyPath_B4F_EventScript_BrailleABC::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleABC, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleABC_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleABC_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleABC_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleABC_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleGHI::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleGHI, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleGHI_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleGHI_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleGHI_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleGHI_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleMNO::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleMNO, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleMNO_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleMNO_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleMNO_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleMNO_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleTUV::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleTUV, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleTUV_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleTUV_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleTUV_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleTUV_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleDEF::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleDEF, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleDEF_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleDEF_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleDEF_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleDEF_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleJKL::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleJKL, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleJKL_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleJKL_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleJKL_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleJKL_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BraillePQRS::
	msgbox MtEmber_RubyPath_B4F_Text_BraillePQRS, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BraillePeriod::
	msgbox MtEmber_RubyPath_B4F_Text_BraillePeriod, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleComma::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleComma, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BraillePQRS_2::
	msgbox MtEmber_RubyPath_B4F_Text_BraillePQRS_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BraillePQRS_3::
	msgbox MtEmber_RubyPath_B4F_Text_BraillePQRS_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleWXYZ, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ_2::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleWXYZ_2, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ_3::
	msgbox MtEmber_RubyPath_B4F_Text_BrailleWXYZ_3, MSGBOX_SIGN
	end

MtEmber_RubyPath_B4F_Text_BrailleABC:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleABC_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleABC_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleGHI:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleGHI_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleGHI_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleMNO:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleMNO_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleMNO_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleTUV:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleTUV_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleTUV_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleDEF:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleDEF_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleDEF_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleJKL:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleJKL_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleJKL_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BraillePQRS:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BraillePeriod:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleComma:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BraillePQRS_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BraillePQRS_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleWXYZ:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleWXYZ_2:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"

MtEmber_RubyPath_B4F_Text_BrailleWXYZ_3:
	.string "Rows of raised dots are cut\ninto the wall. Nobody here\lreads them.$"
