Route35NationalParkGate_MapScripts::
	.byte 0

Route35NationalParkGate_EventScript_BugCatchingContestExplanationSign::
	msgbox Route35NationalParkGate_Text_BugCatchingContestExplanationSign, MSGBOX_SIGN
	end

Route35NationalParkGate_Text_BugCatchingContestExplanationSign:
	.string "The Bug-Catching\nContest is held on\pTuesday, Thursday\nand Saturday.\pNot only do you\nearn a prize just\pfor participating,\nyou also get to\pkeep the bug\nPOKéMON you may\phave at the end of\nthe contest.$"
