RuinsOfAlphOmanyteItemRoom_MapScripts::
	.byte 0

RuinsOfAlphOmanyteItemRoom_EventScript_AncientReplica::
	msgbox RuinsOfAlphOmanyteItemRoom_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphOmanyteItemRoom_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphOmanyteItemRoom_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphOmanyteItemRoom_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphOmanyteItemRoom_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
