BlackthornCity_MapScripts::
	.byte 0

BlackthornCity_EventScript_BlackthornBlackBelt::
	msgbox BlackthornCity_Text_BlackthornBlackBelt, MSGBOX_NPC
	end

BlackthornCity_EventScript_BlackthornCooltrainerF1::
	msgbox BlackthornCity_Text_BlackthornCooltrainerF1, MSGBOX_NPC
	end

BlackthornCity_EventScript_BlackthornYoungster::
	msgbox BlackthornCity_Text_BlackthornYoungster, MSGBOX_NPC
	end

BlackthornCity_EventScript_BlackthornCooltrainerF2::
	msgbox BlackthornCity_Text_BlackthornCooltrainerF2, MSGBOX_NPC
	end

BlackthornCity_EventScript_Sign::
	msgbox BlackthornCity_Text_Sign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_BlackthornGymSign::
	msgbox BlackthornCity_Text_BlackthornGymSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_MoveDeletersHouseSign::
	msgbox BlackthornCity_Text_MoveDeletersHouseSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_DragonDensSign::
	msgbox BlackthornCity_Text_DragonDensSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_TrainerTips::
	msgbox BlackthornCity_Text_TrainerTips, MSGBOX_SIGN
	end

BlackthornCity_Text_BlackthornBlackBelt:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

BlackthornCity_Text_BlackthornCooltrainerF1:
	.string "Are you going to\nmake your POKéMON\lforget some moves?$"

BlackthornCity_Text_BlackthornYoungster:
	.string "Dragon masters all\ncome from the city\lof BLACKTHORN.$"

BlackthornCity_Text_BlackthornCooltrainerF2:
	.string "Wow, you came\nthrough the ICE\lPATH?\pYou must be a real\nhotshot trainer!$"

BlackthornCity_Text_Sign:
	.string "BLACKTHORN CITY\pA Quiet Mountain\nRetreat$"

BlackthornCity_Text_BlackthornGymSign:
	.string "BLACKTHORN CITY\nPOKéMON GYM\lLEADER: CLAIR\pThe Blessed User\nof Dragon POKéMON$"

BlackthornCity_Text_MoveDeletersHouseSign:
	.string "MOVE DELETER'S\nHOUSE$"

BlackthornCity_Text_DragonDensSign:
	.string "DRAGON'S DEN\nAHEAD$"

BlackthornCity_Text_TrainerTips:
	.string "TRAINER TIPS\pA POKéMON holding\na MIRACLEBERRY\pwill cure itself\nof any status\lproblem.$"
