GoldenrodCity_MapScripts::
	.byte 0

GoldenrodCity_EventScript_StationSign::
	msgbox GoldenrodCity_Text_StationSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_RadioTowerSign::
	msgbox GoldenrodCity_Text_RadioTowerSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_GoldenrodDeptStoreSign::
	msgbox GoldenrodCity_Text_GoldenrodDeptStoreSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_GoldenrodGymSign::
	msgbox GoldenrodCity_Text_GoldenrodGymSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_Sign::
	msgbox GoldenrodCity_Text_Sign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_BikeShopSign::
	msgbox GoldenrodCity_Text_BikeShopSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_GameCornerSign::
	msgbox GoldenrodCity_Text_GameCornerSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_NameRaterSign::
	msgbox GoldenrodCity_Text_NameRaterSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_UndergroundSignNorth::
	msgbox GoldenrodCity_Text_UndergroundSignNorth, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_UndergroundSignSouth::
	msgbox GoldenrodCity_Text_UndergroundSignSouth, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_FlowerShopSign::
	msgbox GoldenrodCity_Text_FlowerShopSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_StationSign:
	.string "GOLDENROD CITY\nSTATION$"

GoldenrodCity_Text_RadioTowerSign:
	.string "GOLDENROD CITY\nRADIO TOWER$"

GoldenrodCity_Text_GoldenrodDeptStoreSign:
	.string "Full Selection of\nPOKéMON Goods!\pGOLDENROD CITY\nDEPT.STORE$"

GoldenrodCity_Text_GoldenrodGymSign:
	.string "GOLDENROD CITY\nPOKéMON GYM\lLEADER: WHITNEY\pThe Incredibly\nPretty Girl!$"

GoldenrodCity_Text_Sign:
	.string "GOLDENROD CITY\pThe Festive City\nof Opulent Charm$"

GoldenrodCity_Text_BikeShopSign:
	.string "The World is a\nCycle Path!\lBIKE SHOP$"

GoldenrodCity_Text_GameCornerSign:
	.string "Your Playground!\pGOLDENROD CITY\nGAME CORNER$"

GoldenrodCity_Text_NameRaterSign:
	.string "NAME RATER\pGet Your POKéMON\nNicknames Rated$"

GoldenrodCity_Text_UndergroundSignNorth:
	.string "UNDERGROUND\nENTRANCE$"

GoldenrodCity_Text_UndergroundSignSouth:
	.string "UNDERGROUND\nENTRANCE$"

GoldenrodCity_Text_FlowerShopSign:
	.string "Blooming Beautiful\nFLOWER SHOP$"
