RuinsOfAlphAerodactylItemRoom_MapScripts::
	.byte 0

RuinsOfAlphAerodactylItemRoom_EventScript_AncientReplica::
	msgbox RuinsOfAlphAerodactylItemRoom_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphAerodactylItemRoom_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphAerodactylItemRoom_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphAerodactylItemRoom_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphAerodactylItemRoom_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
