EcruteakCity_MapScripts::
	.byte 0

EcruteakCity_EventScript_Gramps1::
	msgbox EcruteakCity_Text_Gramps1, MSGBOX_NPC
	end

EcruteakCity_EventScript_Gramps2::
	msgbox EcruteakCity_Text_Gramps2, MSGBOX_NPC
	end

EcruteakCity_EventScript_Lass1::
	msgbox EcruteakCity_Text_Lass1, MSGBOX_NPC
	end

EcruteakCity_EventScript_Lass2::
	msgbox EcruteakCity_Text_Lass2, MSGBOX_NPC
	end

EcruteakCity_EventScript_Fisher::
	msgbox EcruteakCity_Text_Fisher, MSGBOX_NPC
	end

EcruteakCity_EventScript_Youngster::
	msgbox EcruteakCity_Text_Youngster, MSGBOX_NPC
	end

EcruteakCity_EventScript_Sign::
	msgbox EcruteakCity_Text_Sign, MSGBOX_SIGN
	end

EcruteakCity_EventScript_TinTowerSign::
	msgbox EcruteakCity_Text_TinTowerSign, MSGBOX_SIGN
	end

EcruteakCity_EventScript_EcruteakGymSign::
	msgbox EcruteakCity_Text_EcruteakGymSign, MSGBOX_SIGN
	end

EcruteakCity_EventScript_EcruteakDanceTheaterSign::
	msgbox EcruteakCity_Text_EcruteakDanceTheaterSign, MSGBOX_SIGN
	end

EcruteakCity_EventScript_BurnedTowerSign::
	msgbox EcruteakCity_Text_BurnedTowerSign, MSGBOX_SIGN
	end

EcruteakCity_Text_Gramps1:
	.string "ECRUTEAK used to\nhave two towers:\pone each in the\neast and west.$"

EcruteakCity_Text_Gramps2:
	.string "Ah, child.\nHave you learned\pto dance like the\nKIMONO GIRLS?\pIf you go to their\nDANCE THEATER, an\podd old man will\ngive you something\lnice, I hear.$"

EcruteakCity_Text_Lass1:
	.string "I'm going to prac-\ntice at the DANCE\pTHEATER. Care to\njoin me?$"

EcruteakCity_Text_Lass2:
	.string "I've lived in JOHTO my whole life.\nNever thought I'd meet someone\lfrom HOENN way out here.$"

EcruteakCity_Text_Fisher:
	.string "Nothing much happens around here,\nbut ever since that ferry started\lrunning to HOENN, who knows.$"

EcruteakCity_Text_Youngster:
	.string "I hear POKéMON are\nrampaging at the\pLAKE OF RAGE. I'd\nlike to see that.$"

EcruteakCity_Text_Sign:
	.string "ECRUTEAK CITY\nA Historical City\pWhere the Past\nMeets the Present$"

EcruteakCity_Text_TinTowerSign:
	.string "TIN TOWER\pA legendary POKé-\nMON is said to\lroost here.$"

EcruteakCity_Text_EcruteakGymSign:
	.string "ECRUTEAK CITY\nPOKéMON GYM\lLEADER: MORTY\pThe Mystic Seer of\nthe Future$"

EcruteakCity_Text_EcruteakDanceTheaterSign:
	.string "ECRUTEAK DANCE\nTHEATER$"

EcruteakCity_Text_BurnedTowerSign:
	.string "BURNED TOWER\pIt was destroyed\nby a mysterious\lfire.\pPlease stay away,\nas it is unsafe.$"
