OlivineMart_MapScripts::
	.byte 0

OlivineMart_EventScript_Clerk::
	msgbox OlivineMart_Text_Clerk, MSGBOX_NPC
	end

OlivineMart_EventScript_CooltrainerF::
	msgbox OlivineMart_Text_CooltrainerF, MSGBOX_NPC
	end

OlivineMart_EventScript_Lass::
	msgbox OlivineMart_Text_Lass, MSGBOX_NPC
	end

OlivineMart_Text_Clerk:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

OlivineMart_Text_CooltrainerF:
	.string "Do your POKéMON\nalready know the\pmove for carrying\npeople on water?$"

OlivineMart_Text_Lass:
	.string "My BUTTERFREE came\nfrom my boyfriend\loverseas.\pIt carried some\nMAIL from him.\pWant to know what\nit says?\pLet's see… Nope!\nIt's a secret!$"
