MtMoon_B2F_MapScripts::
	.byte 0

MtMoon_B2F_EventScript_DomeFossil::
	msgbox MtMoon_B2F_Text_DomeFossil, MSGBOX_NPC
	end

MtMoon_B2F_EventScript_HelixFossil::
	msgbox MtMoon_B2F_Text_HelixFossil, MSGBOX_NPC
	end

MtMoon_B2F_EventScript_Miguel::
	msgbox MtMoon_B2F_Text_Miguel, MSGBOX_NPC
	end

MtMoon_B2F_Text_DomeFossil:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

MtMoon_B2F_Text_HelixFossil:
	.string "Never met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"

MtMoon_B2F_Text_Miguel:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"
