GoldenrodGameCorner_MapScripts::
	.byte 0

GoldenrodGameCorner_EventScript_CoinVendor::
	msgbox GoldenrodGameCorner_Text_CoinVendor, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_TMVendor::
	msgbox GoldenrodGameCorner_Text_TMVendor, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_PrizeMonVendor::
	msgbox GoldenrodGameCorner_Text_PrizeMonVendor, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_Pharmacist::
	msgbox GoldenrodGameCorner_Text_Pharmacist, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_Pharmacist_2::
	msgbox GoldenrodGameCorner_Text_Pharmacist_2, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_PokefanM1::
	msgbox GoldenrodGameCorner_Text_PokefanM1, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_CooltrainerM::
	msgbox GoldenrodGameCorner_Text_CooltrainerM, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_PokefanF::
	msgbox GoldenrodGameCorner_Text_PokefanF, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_CooltrainerF::
	msgbox GoldenrodGameCorner_Text_CooltrainerF, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_Gentleman::
	msgbox GoldenrodGameCorner_Text_Gentleman, MSGBOX_NPC
	end

GoldenrodGameCorner_EventScript_PokefanM2::
	msgbox GoldenrodGameCorner_Text_PokefanM2, MSGBOX_NPC
	end

GoldenrodGameCorner_Text_CoinVendor:
	.string "They say the HOENN champion's\njourney is just getting started.\lWonder where they'll go next.$"

GoldenrodGameCorner_Text_TMVendor:
	.string "JOHTO's changed a lot since the\nHOENN champion opened the sea\lroutes here.$"

GoldenrodGameCorner_Text_PrizeMonVendor:
	.string "Word is a strong trainer crossed\nthe sea from HOENN. I wonder if\lthey'll pass through JOHTO too.$"

GoldenrodGameCorner_Text_Pharmacist:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

GoldenrodGameCorner_Text_Pharmacist_2:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

GoldenrodGameCorner_Text_PokefanM1:
	.string "This route sure gets more foot\ntraffic now that HOENN trainers\lkeep showing up.$"

GoldenrodGameCorner_Text_CooltrainerM:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

GoldenrodGameCorner_Text_PokefanF:
	.string "Nothing much happens around here,\nbut ever since that ferry started\lrunning to HOENN, who knows.$"

GoldenrodGameCorner_Text_CooltrainerF:
	.string "I won't quit until\nI win!$"

GoldenrodGameCorner_Text_Gentleman:
	.string "Nothing much happens around here,\nbut ever since that ferry started\lrunning to HOENN, who knows.$"

GoldenrodGameCorner_Text_PokefanM2:
	.string "They say the HOENN champion's\njourney is just getting started.\lWonder where they'll go next.$"
