PewterCity_MapScripts::
	.byte 0

PewterCity_EventScript_Lass::
	msgbox PewterCity_Text_Lass, MSGBOX_NPC
	end

PewterCity_EventScript_MuseumGuide::
	msgbox PewterCity_Text_MuseumGuide, MSGBOX_NPC
	end

PewterCity_EventScript_FatMan::
	msgbox PewterCity_Text_FatMan, MSGBOX_NPC
	end

PewterCity_EventScript_BugCatcher::
	msgbox PewterCity_Text_BugCatcher, MSGBOX_NPC
	end

PewterCity_EventScript_GymGuide::
	msgbox PewterCity_Text_GymGuide, MSGBOX_NPC
	end

PewterCity_EventScript_RunningShoesAide::
	msgbox PewterCity_Text_RunningShoesAide, MSGBOX_NPC
	end

PewterCity_EventScript_MuseumSign::
	msgbox PewterCity_Text_MuseumSign, MSGBOX_SIGN
	end

PewterCity_EventScript_PoliceNotice::
	msgbox PewterCity_Text_PoliceNotice, MSGBOX_SIGN
	end

PewterCity_EventScript_GymSign::
	msgbox PewterCity_Text_GymSign, MSGBOX_SIGN
	end

PewterCity_EventScript_TrainerTips::
	msgbox PewterCity_Text_TrainerTips, MSGBOX_SIGN
	end

PewterCity_EventScript_CitySign::
	msgbox PewterCity_Text_CitySign, MSGBOX_SIGN
	end

PewterCity_Text_Lass:
	.string "CLEFAIRY came from the moon.\nThat's what the rumor is.\pThey appeared after MOON STONES\nfell on MT. MOON.$"

PewterCity_Text_MuseumGuide:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

PewterCity_Text_FatMan:
	.string "This route's seen more foot traffic\nlately. Something about a champion\lpassing through from JOHTO.$"

PewterCity_Text_BugCatcher:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

PewterCity_Text_GymGuide:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

PewterCity_Text_RunningShoesAide:
	.string "KANTO's a long way from HOENN,\nbut word of that champion still\lmade it all the way here.$"

PewterCity_Text_MuseumSign:
	.string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_PoliceNotice:
	.string "NOTICE!\pThieves have been stealing POKéMON\nfossils from MT. MOON.\pPlease call the PEWTER POLICE if\nyou have any information.$"

PewterCity_Text_GymSign:
	.string "KANTO's a long way from HOENN,\nbut word of that champion still\lmade it all the way here.$"

PewterCity_Text_TrainerTips:
	.string "TRAINER TIPS\pAll POKéMON that appear in battle,\nhowever briefly, earn EXP Points.$"

PewterCity_Text_CitySign:
	.string "PEWTER CITY\nA Stone Gray City$"
