PewterCity_MapScripts::
	.byte 0

PewterCity_EventScript_Lass::
	msgbox PewterCity_Text_Lass, MSGBOX_NPC
	end

PewterCity_EventScript_MuseumGuide::
	msgbox PewterCity_Text_MuseumGuide, MSGBOX_NPC
	end

PewterCity_EventScript_FatMan::
	msgbox PewterCity_Text_FatMan, MSGBOX_NPC
	end

PewterCity_EventScript_BugCatcher::
	msgbox PewterCity_Text_BugCatcher, MSGBOX_NPC
	end

PewterCity_EventScript_GymGuide::
	msgbox PewterCity_Text_GymGuide, MSGBOX_NPC
	end

PewterCity_EventScript_RunningShoesAide::
	msgbox PewterCity_Text_RunningShoesAide, MSGBOX_NPC
	end

PewterCity_EventScript_MuseumSign::
	msgbox PewterCity_Text_MuseumSign, MSGBOX_SIGN
	end

PewterCity_EventScript_PoliceNotice::
	msgbox PewterCity_Text_PoliceNotice, MSGBOX_SIGN
	end

PewterCity_EventScript_GymSign::
	msgbox PewterCity_Text_GymSign, MSGBOX_SIGN
	end

PewterCity_EventScript_TrainerTips::
	msgbox PewterCity_Text_TrainerTips, MSGBOX_SIGN
	end

PewterCity_EventScript_CitySign::
	msgbox PewterCity_Text_CitySign, MSGBOX_SIGN
	end

PewterCity_Text_Lass:
	.string "CLEFAIRY came from the moon.\nThat's what the rumor is.\pThey appeared after MOON STONES\nfell on MT. MOON.$"

PewterCity_Text_MuseumGuide:
	.string "The MUSEUM is shut. The fossils\ninside don't care what you've won.$"

PewterCity_Text_FatMan:
	.string "There aren't many serious POKéMON\nTRAINERS here.\pThey're all like BUG CATCHERS,\nyou know, just hobbyists.\pBut PEWTER GYM's BROCK isn't like\nthat, not one bit.$"

PewterCity_Text_BugCatcher:
	.string "I catch bugs. You catch Leagues.\nNeither of us is impressed.$"

PewterCity_Text_GymGuide:
	.string "BROCK is inside. I'm not walking\nyou there. You know the way.$"

PewterCity_Text_RunningShoesAide:
	.string "You already move faster than\nanyone I've fitted shoes for.$"

PewterCity_Text_MuseumSign:
	.string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_PoliceNotice:
	.string "NOTICE!\pThieves have been stealing POKéMON\nfossils from MT. MOON.\pPlease call the PEWTER POLICE if\nyou have any information.$"

PewterCity_Text_GymSign:
	.string "PEWTER CITY POKéMON GYM\nLEADER: BROCK\lThe Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_TrainerTips:
	.string "TRAINER TIPS\pAll POKéMON that appear in battle,\nhowever briefly, earn EXP Points.$"

PewterCity_Text_CitySign:
	.string "PEWTER CITY\nA Stone Gray City$"
