CeladonCity_Condominiums_2F_MapScripts::
	.byte 0

CeladonCity_Condominiums_2F_EventScript_MeetingRoomSign::
	msgbox CeladonCity_Condominiums_2F_Text_MeetingRoomSign, MSGBOX_SIGN
	end

CeladonCity_Condominiums_2F_EventScript_MeetingRoomSign_2::
	msgbox CeladonCity_Condominiums_2F_Text_MeetingRoomSign_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_2F_Text_MeetingRoomSign:
	.string "GAME FREAK Meeting Room$"

CeladonCity_Condominiums_2F_Text_MeetingRoomSign_2:
	.string "GAME FREAK Meeting Room$"
