PalletTown_ProfessorOaksLab_MapScripts::
	.byte 0

PalletTown_ProfessorOaksLab_EventScript_Aide1::
	msgbox PalletTown_ProfessorOaksLab_Text_Aide1, MSGBOX_NPC
	end

PalletTown_ProfessorOaksLab_EventScript_Aide3::
	msgbox PalletTown_ProfessorOaksLab_Text_Aide3, MSGBOX_NPC
	end

PalletTown_ProfessorOaksLab_EventScript_Aide2::
	msgbox PalletTown_ProfessorOaksLab_Text_Aide2, MSGBOX_NPC
	end

PalletTown_ProfessorOaksLab_EventScript_Computer::
	msgbox PalletTown_ProfessorOaksLab_Text_Computer, MSGBOX_SIGN
	end

PalletTown_ProfessorOaksLab_EventScript_Computer_2::
	msgbox PalletTown_ProfessorOaksLab_Text_Computer_2, MSGBOX_SIGN
	end

PalletTown_ProfessorOaksLab_EventScript_LeftSign::
	msgbox PalletTown_ProfessorOaksLab_Text_LeftSign, MSGBOX_SIGN
	end

PalletTown_ProfessorOaksLab_EventScript_RightSign::
	msgbox PalletTown_ProfessorOaksLab_Text_RightSign, MSGBOX_SIGN
	end

PalletTown_ProfessorOaksLab_Text_Aide1:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

PalletTown_ProfessorOaksLab_Text_Aide3:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

PalletTown_ProfessorOaksLab_Text_Aide2:
	.string "Never met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"

PalletTown_ProfessorOaksLab_Text_Computer:
	.string "There's an e-mail message here.\p…\pFinally!\nThe ultimate TRAINERS of the\lPOKéMON LEAGUE are ready to\ltake on all comers!\pBring your best POKéMON and see\nhow you rate as a TRAINER!\pPOKéMON LEAGUE HQ\nINDIGO PLATEAU\pPROF. OAK, please visit us!\n…$"

PalletTown_ProfessorOaksLab_Text_Computer_2:
	.string "There's an e-mail message here.\p…\pFinally!\nThe ultimate TRAINERS of the\lPOKéMON LEAGUE are ready to\ltake on all comers!\pBring your best POKéMON and see\nhow you rate as a TRAINER!\pPOKéMON LEAGUE HQ\nINDIGO PLATEAU\pPROF. OAK, please visit us!\n…$"

PalletTown_ProfessorOaksLab_Text_LeftSign:
	.string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_RightSign:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"
