SafariZone_Center_RestHouse_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_RestHouse_Text_Scientist, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_RestHouse_Text_Sara, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_Text_Scientist:
	.string "I'm catching POKéMON to take home\nas gifts.$"

SafariZone_Center_RestHouse_Text_Sara:
	.string "SARA: Where did my boyfriend,\nERIK, go?$"
