Route29_MapScripts::
	.byte 0

Route29_EventScript_CatchingTutorialDude::
	msgbox Route29_Text_CatchingTutorialDude, MSGBOX_NPC
	end

Route29_EventScript_Youngster::
	msgbox Route29_Text_Youngster, MSGBOX_NPC
	end

Route29_EventScript_Teacher::
	msgbox Route29_Text_Teacher, MSGBOX_NPC
	end

Route29_EventScript_Fisher::
	msgbox Route29_Text_Fisher, MSGBOX_NPC
	end

Route29_EventScript_CooltrainerM::
	msgbox Route29_Text_CooltrainerM, MSGBOX_NPC
	end

Route29_EventScript_Sign1::
	msgbox Route29_Text_Sign1, MSGBOX_SIGN
	end

Route29_EventScript_Sign2::
	msgbox Route29_Text_Sign2, MSGBOX_SIGN
	end

Route29_Text_CatchingTutorialDude:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"

Route29_Text_Youngster:
	.string "Yo. How are your\nPOKéMON?\pIf they're weak\nand not ready for\pbattle, keep out\nof the grass.$"

Route29_Text_Teacher:
	.string "See those ledges?\nIt's scary to jump\loff them.\pBut you can go to\nNEW BARK without\pwalking through\nthe grass.$"

Route29_Text_Fisher:
	.string "I wanted to take a\nbreak, so I saved\pto record my\nprogress.$"

Route29_Text_CooltrainerM:
	.string "This route sure gets more foot\ntraffic now that HOENN trainers\lkeep showing up.$"

Route29_Text_Sign1:
	.string "ROUTE 29\pCHERRYGROVE CITY -\nNEW BARK TOWN$"

Route29_Text_Sign2:
	.string "ROUTE 29\pCHERRYGROVE CITY -\nNEW BARK TOWN$"
