GoldenrodDeptStoreRoof_MapScripts::
	.byte 0

GoldenrodDeptStoreRoof_EventScript_PokefanF::
	msgbox GoldenrodDeptStoreRoof_Text_PokefanF, MSGBOX_NPC
	end

GoldenrodDeptStoreRoof_EventScript_Fisher::
	msgbox GoldenrodDeptStoreRoof_Text_Fisher, MSGBOX_NPC
	end

GoldenrodDeptStoreRoof_Text_PokefanF:
	.string "Whew, I'm tired.\pI sometimes come\nup to the rooftop\pto take a break\nfrom shopping.$"

GoldenrodDeptStoreRoof_Text_Fisher:
	.string "I've been wandering these routes\nfor years. Lately there's talk of\lnothing but the HOENN champion.$"
