RuinsOfAlphKabutoChamber_MapScripts::
	.byte 0

RuinsOfAlphKabutoChamber_EventScript_Scientist::
	msgbox RuinsOfAlphKabutoChamber_Text_Scientist, MSGBOX_NPC
	end

RuinsOfAlphKabutoChamber_EventScript_AncientReplica::
	msgbox RuinsOfAlphKabutoChamber_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphKabutoChamber_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphKabutoChamber_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphKabutoChamber_Text_Scientist:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

RuinsOfAlphKabutoChamber_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphKabutoChamber_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
