Route39Barn_MapScripts::
	.byte 0

Route39Barn_EventScript_Twin1::
	msgbox Route39Barn_Text_Twin1, MSGBOX_NPC
	end

Route39Barn_EventScript_Twin2::
	msgbox Route39Barn_Text_Twin2, MSGBOX_NPC
	end

Route39Barn_Text_Twin1:
	.string "I've lived in JOHTO my whole life.\nNever thought I'd meet someone\lfrom HOENN way out here.$"

Route39Barn_Text_Twin2:
	.string "I've lived in JOHTO my whole life.\nNever thought I'd meet someone\lfrom HOENN way out here.$"
