ViridianCity_School_MapScripts::
	.byte 0

ViridianCity_School_EventScript_Woman::
	msgbox ViridianCity_School_Text_Woman, MSGBOX_NPC
	end

ViridianCity_School_EventScript_Lass::
	msgbox ViridianCity_School_Text_Lass, MSGBOX_NPC
	end

ViridianCity_School_EventScript_Notebook::
	msgbox ViridianCity_School_Text_Notebook, MSGBOX_SIGN
	end

ViridianCity_School_EventScript_Blackboard::
	msgbox ViridianCity_School_Text_Blackboard, MSGBOX_SIGN
	end

ViridianCity_School_EventScript_Blackboard_2::
	msgbox ViridianCity_School_Text_Blackboard_2, MSGBOX_SIGN
	end

ViridianCity_School_Text_Woman:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

ViridianCity_School_Text_Lass:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

ViridianCity_School_Text_Notebook:
	.string "This route's seen more foot traffic\nlately. Something about a champion\lpassing through from JOHTO.$"

ViridianCity_School_Text_Blackboard:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

ViridianCity_School_Text_Blackboard_2:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"
