LavenderTown_VolunteerPokemonHouse_MapScripts::
	.byte 0

LavenderTown_VolunteerPokemonHouse_EventScript_LittleBoy::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_LittleBoy, MSGBOX_NPC
	end

LavenderTown_VolunteerPokemonHouse_EventScript_Youngster::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_Youngster, MSGBOX_NPC
	end

LavenderTown_VolunteerPokemonHouse_EventScript_LittleGirl::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_LittleGirl, MSGBOX_NPC
	end

LavenderTown_VolunteerPokemonHouse_EventScript_PokemonFanMagazine::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_PokemonFanMagazine, MSGBOX_SIGN
	end

LavenderTown_VolunteerPokemonHouse_EventScript_Bookshelf::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_Bookshelf, MSGBOX_SIGN
	end

LavenderTown_VolunteerPokemonHouse_EventScript_Bookshelf_2::
	msgbox LavenderTown_VolunteerPokemonHouse_Text_Bookshelf_2, MSGBOX_SIGN
	end

LavenderTown_VolunteerPokemonHouse_Text_LittleBoy:
	.string "It's so warm!\nPOKéMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Youngster:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

LavenderTown_VolunteerPokemonHouse_Text_LittleGirl:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonFanMagazine:
	.string "This route's seen more foot traffic\nlately. Something about a champion\lpassing through from JOHTO.$"

LavenderTown_VolunteerPokemonHouse_Text_Bookshelf:
	.string "POKéMON magazines line the shelf.\pPOKéMON INSIDER…\pPOKéMON FAN…$"

LavenderTown_VolunteerPokemonHouse_Text_Bookshelf_2:
	.string "POKéMON magazines line the shelf.\pPOKéMON INSIDER…\pPOKéMON FAN…$"
