RuinsOfAlphInnerChamber_MapScripts::
	.byte 0

RuinsOfAlphInnerChamber_EventScript_Statue::
	msgbox RuinsOfAlphInnerChamber_Text_Statue, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_2::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_2, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_3::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_3, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_4::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_4, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_5::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_5, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_6::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_6, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_7::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_7, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_8::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_8, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_9::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_9, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_10::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_10, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_11::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_11, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_12::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_12, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_13::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_13, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_14::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_14, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_15::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_15, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_16::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_16, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_17::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_17, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_18::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_18, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_19::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_19, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_20::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_20, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_21::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_21, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_22::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_22, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_23::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_23, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_24::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_24, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_25::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_25, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_EventScript_Statue_26::
	msgbox RuinsOfAlphInnerChamber_Text_Statue_26, MSGBOX_SIGN
	end

RuinsOfAlphInnerChamber_Text_Statue:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_3:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_4:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_5:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_6:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_7:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_8:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_9:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_10:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_11:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_12:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_13:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_14:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_15:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_16:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_17:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_18:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_19:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_20:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_21:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_22:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_23:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_24:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_25:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphInnerChamber_Text_Statue_26:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
