EarlsPokemonAcademy_MapScripts::
	.byte 0

EarlsPokemonAcademy_EventScript_Youngster1::
	msgbox EarlsPokemonAcademy_Text_Youngster1, MSGBOX_NPC
	end

EarlsPokemonAcademy_EventScript_Youngster2::
	msgbox EarlsPokemonAcademy_Text_Youngster2, MSGBOX_NPC
	end

EarlsPokemonAcademy_Text_Youngster1:
	.string "I'm taking notes\nof the teacher's\llecture.\pI'd better copy\nthe stuff on the\lblackboard too.$"

EarlsPokemonAcademy_Text_Youngster2:
	.string "A POKéMON holding\na BERRY will heal\litself in battle.\pMany other items\ncan be held by\lPOKéMON…\pIt sure is tough\ntaking notes…$"
