CeladonCity_Condominiums_RoofRoom_MapScripts::
	.byte 0

CeladonCity_Condominiums_RoofRoom_EventScript_BlackBelt::
	msgbox CeladonCity_Condominiums_RoofRoom_Text_BlackBelt, MSGBOX_NPC
	end

CeladonCity_Condominiums_RoofRoom_EventScript_Blackboard::
	msgbox CeladonCity_Condominiums_RoofRoom_Text_Blackboard, MSGBOX_SIGN
	end

CeladonCity_Condominiums_RoofRoom_EventScript_Blackboard_2::
	msgbox CeladonCity_Condominiums_RoofRoom_Text_Blackboard_2, MSGBOX_SIGN
	end

CeladonCity_Condominiums_RoofRoom_EventScript_TMsPamphlet::
	msgbox CeladonCity_Condominiums_RoofRoom_Text_TMsPamphlet, MSGBOX_SIGN
	end

CeladonCity_Condominiums_RoofRoom_Text_BlackBelt:
	.string "There is nothing that I don't know,\nlike I wrote on the blackboard.\pI know about the world of POKéMON\nin your GAME BOY ADVANCE!\pGet together with your friends and\nenjoy trading POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_Blackboard:
	.string "A board of rules for linking up\nwith other trainers. KANTO has\lnobody to link you to.$"

CeladonCity_Condominiums_RoofRoom_Text_Blackboard_2:
	.string "A board of rules for linking up\nwith other trainers. KANTO has\lnobody to link you to.$"

CeladonCity_Condominiums_RoofRoom_Text_TMsPamphlet:
	.string "It's a pamphlet on TMs.\p… …\pThere are fifty TMs in all.\pThere are also seven HMs that\ncan be used repeatedly.\pSILPH CO.$"
