CeladonCity_GameCorner_PrizeRoom_MapScripts::
	.byte 0

CeladonCity_GameCorner_PrizeRoom_EventScript_BaldingMan::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_BaldingMan, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_OldMan::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_OldMan, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkMons::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkMons, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkTMs::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkTMs, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkItems::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkItems, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_Text_BaldingMan:
	.string "I sure do fancy that PORYGON!\nBut, it's hard to win at slots!$"

CeladonCity_GameCorner_PrizeRoom_Text_OldMan:
	.string "Gahaha! I raked it in today!\nIf only every day were like this…$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkMons:
	.string "The prize shelves are empty.\nWhoever ran this floor is gone.$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkTMs:
	.string "The prize shelves are empty.\nWhoever ran this floor is gone.$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkItems:
	.string "The prize shelves are empty.\nWhoever ran this floor is gone.$"
