CeladonCity_GameCorner_PrizeRoom_MapScripts::
	.byte 0

CeladonCity_GameCorner_PrizeRoom_EventScript_BaldingMan::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_BaldingMan, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_OldMan::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_OldMan, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkMons::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkMons, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkTMs::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkTMs, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkItems::
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkItems, MSGBOX_NPC
	end

CeladonCity_GameCorner_PrizeRoom_Text_BaldingMan:
	.string "I sure do fancy that PORYGON!\nBut, it's hard to win at slots!$"

CeladonCity_GameCorner_PrizeRoom_Text_OldMan:
	.string "Gahaha! I raked it in today!\nIf only every day were like this…$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkMons:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkTMs:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

CeladonCity_GameCorner_PrizeRoom_Text_PrizeClerkItems:
	.string "KANTO's a long way from HOENN,\nbut word of that champion still\lmade it all the way here.$"
