MrPokemonsHouse_MapScripts::
	.byte 0

MrPokemonsHouse_EventScript__MrPokemon::
	msgbox MrPokemonsHouse_Text__MrPokemon, MSGBOX_NPC
	end

MrPokemonsHouse_EventScript__ForeignMagazines::
	msgbox MrPokemonsHouse_Text__ForeignMagazines, MSGBOX_SIGN
	end

MrPokemonsHouse_EventScript__ForeignMagazines_2::
	msgbox MrPokemonsHouse_Text__ForeignMagazines_2, MSGBOX_SIGN
	end

MrPokemonsHouse_EventScript__BrokenComputer::
	msgbox MrPokemonsHouse_Text__BrokenComputer, MSGBOX_SIGN
	end

MrPokemonsHouse_EventScript__BrokenComputer_2::
	msgbox MrPokemonsHouse_Text__BrokenComputer_2, MSGBOX_SIGN
	end

MrPokemonsHouse_EventScript__StrangeCoins::
	msgbox MrPokemonsHouse_Text__StrangeCoins, MSGBOX_SIGN
	end

MrPokemonsHouse_Text__MrPokemon:
	.string "Word is a strong trainer crossed\nthe sea from HOENN. I wonder if\lthey'll pass through JOHTO too.$"

MrPokemonsHouse_Text__ForeignMagazines:
	.string "It's packed with\nforeign magazines.\pCan't even read\ntheir titles…$"

MrPokemonsHouse_Text__ForeignMagazines_2:
	.string "It's packed with\nforeign magazines.\pCan't even read\ntheir titles…$"

MrPokemonsHouse_Text__BrokenComputer:
	.string "It's a big com-\nputer. Hmm. It's\lbroken.$"

MrPokemonsHouse_Text__BrokenComputer_2:
	.string "It's a big com-\nputer. Hmm. It's\lbroken.$"

MrPokemonsHouse_Text__StrangeCoins:
	.string "A whole pile of\nstrange coins!\pMaybe they're from\nanother country…$"
