MahoganyPokecenter1F_MapScripts::
	.byte 0

MahoganyPokecenter1F_EventScript_Nurse::
	msgbox MahoganyPokecenter1F_Text_Nurse, MSGBOX_NPC
	end

MahoganyPokecenter1F_EventScript_PokefanM::
	msgbox MahoganyPokecenter1F_Text_PokefanM, MSGBOX_NPC
	end

MahoganyPokecenter1F_EventScript_Youngster::
	msgbox MahoganyPokecenter1F_Text_Youngster, MSGBOX_NPC
	end

MahoganyPokecenter1F_EventScript_CooltrainerF::
	msgbox MahoganyPokecenter1F_Text_CooltrainerF, MSGBOX_NPC
	end

MahoganyPokecenter1F_Text_Nurse:
	.string "Nothing much happens around here,\nbut ever since that ferry started\lrunning to HOENN, who knows.$"

MahoganyPokecenter1F_Text_PokefanM:
	.string "What's this? TEAM\nROCKET has come\lback?\pI saw some men in\nblack at LAKE OF\lRAGE…$"

MahoganyPokecenter1F_Text_Youngster:
	.string "I stop my POKéMON\nfrom evolving too\learly.\pI make them learn\ncertain moves be-\lfore I let them\levolve.$"

MahoganyPokecenter1F_Text_CooltrainerF:
	.string "POKéMON do become\nstronger when they\pevolve, but they\nalso learn moves\lmore slowly.$"
