SSAnne_1F_Room3_MapScripts::
	.byte 0

SSAnne_1F_Room3_EventScript_LittleGirl::
	msgbox SSAnne_1F_Room3_Text_LittleGirl, MSGBOX_NPC
	end

SSAnne_1F_Room3_EventScript_BaldingMan::
	msgbox SSAnne_1F_Room3_Text_BaldingMan, MSGBOX_NPC
	end

SSAnne_1F_Room3_Text_LittleGirl:
	.string "I always travel with WIGGLYTUFF.\nI never leave home without it.$"

SSAnne_1F_Room3_Text_BaldingMan:
	.string "A world cruise is so elegant yet\ncozy!$"
