CeladonCity_DepartmentStore_Elevator_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_Elevator_EventScript_FloorSelect::
	msgbox CeladonCity_DepartmentStore_Elevator_Text_FloorSelect, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Elevator_EventScript_FloorSelect_2::
	msgbox CeladonCity_DepartmentStore_Elevator_Text_FloorSelect_2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Elevator_Text_FloorSelect:
	.string "KANTO's got its own trainers worth\nwatching, but even we're curious\labout this HOENN-JOHTO champion.$"

CeladonCity_DepartmentStore_Elevator_Text_FloorSelect_2:
	.string "KANTO's got its own trainers worth\nwatching, but even we're curious\labout this HOENN-JOHTO champion.$"
