CeladonCity_DepartmentStore_Elevator_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_Elevator_EventScript_FloorSelect::
	msgbox CeladonCity_DepartmentStore_Elevator_Text_FloorSelect, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Elevator_EventScript_FloorSelect_2::
	msgbox CeladonCity_DepartmentStore_Elevator_Text_FloorSelect_2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_Elevator_Text_FloorSelect:
	.string "The floor panel is dark.\nThe stairs still work.$"

CeladonCity_DepartmentStore_Elevator_Text_FloorSelect_2:
	.string "The floor panel is dark.\nThe stairs still work.$"
