PokemonTower_1F_MapScripts::
	.byte 0

PokemonTower_1F_EventScript_WorkerF::
	msgbox PokemonTower_1F_Text_WorkerF, MSGBOX_NPC
	end

PokemonTower_1F_EventScript_Channeler::
	msgbox PokemonTower_1F_Text_Channeler, MSGBOX_NPC
	end

PokemonTower_1F_EventScript_Woman1::
	msgbox PokemonTower_1F_Text_Woman1, MSGBOX_NPC
	end

PokemonTower_1F_EventScript_Woman2::
	msgbox PokemonTower_1F_Text_Woman2, MSGBOX_NPC
	end

PokemonTower_1F_EventScript_BaldingMan::
	msgbox PokemonTower_1F_Text_BaldingMan, MSGBOX_NPC
	end

PokemonTower_1F_Text_WorkerF:
	.string "POKéMON TOWER was erected in the\nmemory of POKéMON that died.$"

PokemonTower_1F_Text_Channeler:
	.string "I am a CHANNELER.\pThere are spirits up to mischief.\nI sense them high in the TOWER.$"

PokemonTower_1F_Text_Woman1:
	.string "My GROWLITHE…\nWhy did you die?$"

PokemonTower_1F_Text_Woman2:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

PokemonTower_1F_Text_BaldingMan:
	.string "I came to pray for my dearly\ndeparted CLEFAIRY.\pSniff!\nI'm awash in tears…$"
