CherrygroveGymSpeechHouse_MapScripts::
	.byte 0

CherrygroveGymSpeechHouse_EventScript_PokefanM::
	msgbox CherrygroveGymSpeechHouse_Text_PokefanM, MSGBOX_NPC
	end

CherrygroveGymSpeechHouse_EventScript_BugCatcher::
	msgbox CherrygroveGymSpeechHouse_Text_BugCatcher, MSGBOX_NPC
	end

CherrygroveGymSpeechHouse_Text_PokefanM:
	.string "You're trying to\nsee how good you\pare as a POKéMON\ntrainer?\pYou better visit\nthe POKéMON GYMS\pall over JOHTO and\ncollect BADGES.$"

CherrygroveGymSpeechHouse_Text_BugCatcher:
	.string "When I get older,\nI'm going to be a\lGYM LEADER!\pI make my POKéMON\nbattle with my\pfriend's to make\nthem tougher!$"
