FuchsiaCity_SafariZone_Office_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_Worker2, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_Worker3, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_Worker1, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_Worker4, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_Worker2:
	.string "WARDEN SLOWPOKE is very\nknowledgeable about POKéMON.\pHe even has some fossils of rare,\nextinct POKéMON.$"

FuchsiaCity_SafariZone_Office_Text_Worker3:
	.string "WARDEN SLOWPOKE came in, but\nI couldn't understand him.\pI think he's got a speech problem!$"

FuchsiaCity_SafariZone_Office_Text_Worker1:
	.string "We nicknamed the WARDEN\n“SLOWPOKE.”\pYou know, he has that vacant look\nlike a SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_Worker4:
	.string "WARDEN SLOWPOKE is running a\npromotion campaign right now.\pTry to get to the farthest corner\nof the SAFARI ZONE.\pIf you can make it, you'll win a\nvery convenient prize.$"
