Route35GoldenrodGate_MapScripts::
	.byte 0

Route35GoldenrodGate_EventScript_Randy::
	msgbox Route35GoldenrodGate_Text_Randy, MSGBOX_NPC
	end

Route35GoldenrodGate_EventScript_PokefanF::
	msgbox Route35GoldenrodGate_Text_PokefanF, MSGBOX_NPC
	end

Route35GoldenrodGate_EventScript_Fisher::
	msgbox Route35GoldenrodGate_Text_Fisher, MSGBOX_NPC
	end

Route35GoldenrodGate_Text_Randy:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"

Route35GoldenrodGate_Text_PokefanF:
	.string "This route sure gets more foot\ntraffic now that HOENN trainers\lkeep showing up.$"

Route35GoldenrodGate_Text_Fisher:
	.string "I wonder how many\nkinds of POKéMON\pthere are in the\nworld.\pThree years ago,\nPROF.OAK said that\pthere were 150\ndifferent kinds.$"
