LakeOfRage_MapScripts::
	.byte 0

LakeOfRage_EventScript_Gramps::
	msgbox LakeOfRage_Text_Gramps, MSGBOX_NPC
	end

LakeOfRage_EventScript_SuperNerd::
	msgbox LakeOfRage_Text_SuperNerd, MSGBOX_NPC
	end

LakeOfRage_EventScript_CooltrainerF::
	msgbox LakeOfRage_Text_CooltrainerF, MSGBOX_NPC
	end

LakeOfRage_EventScript_Sign::
	msgbox LakeOfRage_Text_Sign, MSGBOX_SIGN
	end

LakeOfRage_Text_Gramps:
	.string "The old timers say JOHTO used to\nfeel far from everywhere. Not\lanymore, with HOENN so close now.$"

LakeOfRage_Text_SuperNerd:
	.string "I heard this lake\nwas made by ram-\lpaging GYARADOS.\pI wonder if there\nis any connection\pto their mass out-\nbreak now?$"

LakeOfRage_Text_CooltrainerF:
	.string "Did my eyes de-\nceive me? I saw a\pred GYARADOS in\nthe LAKE…\pBut I thought\nGYARADOS were\lusually blue?$"

LakeOfRage_Text_Sign:
	.string "LAKE OF RAGE,\nalso known as\lGYARADOS LAKE.$"
