CeruleanCity_MapScripts::
	.byte 0

CeruleanCity_EventScript_Policeman::
	msgbox CeruleanCity_Text_Policeman, MSGBOX_NPC
	end

CeruleanCity_EventScript_LittleBoy::
	msgbox CeruleanCity_Text_LittleBoy, MSGBOX_NPC
	end

CeruleanCity_EventScript_BaldingMan::
	msgbox CeruleanCity_Text_BaldingMan, MSGBOX_NPC
	end

CeruleanCity_EventScript_Lass::
	msgbox CeruleanCity_Text_Lass, MSGBOX_NPC
	end

CeruleanCity_EventScript_Youngster::
	msgbox CeruleanCity_Text_Youngster, MSGBOX_NPC
	end

CeruleanCity_EventScript_Woman::
	msgbox CeruleanCity_Text_Woman, MSGBOX_NPC
	end

CeruleanCity_EventScript_CeruleanCaveGuard::
	msgbox CeruleanCity_Text_CeruleanCaveGuard, MSGBOX_NPC
	end

CeruleanCity_EventScript_CitySign::
	msgbox CeruleanCity_Text_CitySign, MSGBOX_SIGN
	end

CeruleanCity_EventScript_GymSign::
	msgbox CeruleanCity_Text_GymSign, MSGBOX_SIGN
	end

CeruleanCity_EventScript_BikeShopSign::
	msgbox CeruleanCity_Text_BikeShopSign, MSGBOX_SIGN
	end

CeruleanCity_EventScript_TrainerTips::
	msgbox CeruleanCity_Text_TrainerTips, MSGBOX_SIGN
	end

CeruleanCity_Text_Policeman:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"

CeruleanCity_Text_LittleBoy:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

CeruleanCity_Text_BaldingMan:
	.string "You're making an encyclopedia on\nPOKéMON? That sounds amusing.$"

CeruleanCity_Text_Lass:
	.string "Never met the champion myself.\nHeard they came up through HOENN\land JOHTO before setting foot here.$"

CeruleanCity_Text_Youngster:
	.string "You're a TRAINER, too?\pCollecting, battling…\nIt's a tough life, isn't it?$"

CeruleanCity_Text_Woman:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeruleanCity_Text_CeruleanCaveGuard:
	.string "This is CERULEAN CAVE.\pHorribly strong POKéMON live inside\nthere.\pIt takes a very special TRAINER to\nbe allowed inside there.\pYou'd have to be strong enough to\nbecome the POKéMON LEAGUE\lCHAMPION for starters.\pAnd, you would have to have\nmade a great achievement.$"

CeruleanCity_Text_CitySign:
	.string "CERULEAN CITY\nA Mysterious, Blue Aura Surrounds\lIt$"

CeruleanCity_Text_GymSign:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

CeruleanCity_Text_BikeShopSign:
	.string "Grass and caves handled easily!\nBIKE SHOP$"

CeruleanCity_Text_TrainerTips:
	.string "TRAINER TIPS\pA POKéMON can be made to hold\nan item.\pSome items can even be used by\nthe holding POKéMON in battle.$"
