OlivineCafe_MapScripts::
	.byte 0

OlivineCafe_EventScript_StrengthSailor::
	msgbox OlivineCafe_Text_StrengthSailor, MSGBOX_NPC
	end

OlivineCafe_EventScript_FishingGuru::
	msgbox OlivineCafe_Text_FishingGuru, MSGBOX_NPC
	end

OlivineCafe_EventScript_Sailor::
	msgbox OlivineCafe_Text_Sailor, MSGBOX_NPC
	end

OlivineCafe_Text_StrengthSailor:
	.string "My grandkids won't stop talking\nabout the new champion from over\lin HOENN. Kids these days!$"

OlivineCafe_Text_FishingGuru:
	.string "OLIVINE CAFE's\nmenu is chock full\pof hearty fare for\nbeefy SAILORS!$"

OlivineCafe_Text_Sailor:
	.string "Whenever I roll\ninto this town, I\palways visit the\nOLIVINE CAFE.\pEverything on the\nmenu makes me feel\pstronger. I can't\nstop eating!$"
