CeruleanCity_BikeShop_MapScripts::
	.byte 0

CeruleanCity_BikeShop_EventScript_Clerk::
	msgbox CeruleanCity_BikeShop_Text_Clerk, MSGBOX_NPC
	end

CeruleanCity_BikeShop_EventScript_Youngster::
	msgbox CeruleanCity_BikeShop_Text_Youngster, MSGBOX_NPC
	end

CeruleanCity_BikeShop_EventScript_Woman::
	msgbox CeruleanCity_BikeShop_Text_Woman, MSGBOX_NPC
	end

CeruleanCity_BikeShop_EventScript_Bicycle::
	msgbox CeruleanCity_BikeShop_Text_Bicycle, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_2::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_2, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_3::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_3, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_4::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_4, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_5::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_5, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_6::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_6, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_7::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_7, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle_8::
	msgbox CeruleanCity_BikeShop_Text_Bicycle_8, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_Text_Clerk:
	.string "Nothing on the racks.\nKANTO's bikes went east months\lago and never came back.$"

CeruleanCity_BikeShop_Text_Youngster:
	.string "I come in to look. There's\nnothing on the racks to look at.$"

CeruleanCity_BikeShop_Text_Woman:
	.string "A plain city bike is good enough\nfor me.\pAfter all, you can't put a shopping\nbasket on a mountain bike.$"

CeruleanCity_BikeShop_Text_Bicycle:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_2:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_3:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_4:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_5:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_6:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_7:
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_Bicycle_8:
	.string "A shiny new BICYCLE!$"
