CeruleanCity_House3_MapScripts::
	.byte 0

CeruleanCity_House3_EventScript_Dontae::
	msgbox CeruleanCity_House3_Text_Dontae, MSGBOX_NPC
	end

CeruleanCity_House3_EventScript_OldWoman::
	msgbox CeruleanCity_House3_Text_OldWoman, MSGBOX_NPC
	end

CeruleanCity_House3_Text_Dontae:
	.string "I traded away the one I wanted,\nyears back. Still think on it.$"

CeruleanCity_House3_Text_OldWoman:
	.string "My husband likes trading POKéMON.\pYou're collecting POKéMON for your\nPOKéDEX, aren't you?\pWould you please trade with him?$"
