CeruleanCity_House3_MapScripts::
	.byte 0

CeruleanCity_House3_EventScript_Dontae::
	msgbox CeruleanCity_House3_Text_Dontae, MSGBOX_NPC
	end

CeruleanCity_House3_EventScript_OldWoman::
	msgbox CeruleanCity_House3_Text_OldWoman, MSGBOX_NPC
	end

CeruleanCity_House3_Text_Dontae:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

CeruleanCity_House3_Text_OldWoman:
	.string "My husband likes trading POKéMON.\pYou're collecting POKéMON for your\nPOKéDEX, aren't you?\pWould you please trade with him?$"
