CeladonCity_DepartmentStore_3F_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
	msgbox CeladonCity_DepartmentStore_3F_Text_CounterTutor, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
	msgbox CeladonCity_DepartmentStore_3F_Text_GBAKid1, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
	msgbox CeladonCity_DepartmentStore_3F_Text_GBAKid3, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
	msgbox CeladonCity_DepartmentStore_3F_Text_GBAKid2, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
	msgbox CeladonCity_DepartmentStore_3F_Text_LittleGirl, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_FloorSign, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_TV1, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_TV2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_TV3, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_TV4, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_SuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES_2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SuperNES_2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES_3::
	msgbox CeladonCity_DepartmentStore_3F_Text_SuperNES_3, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES_4::
	msgbox CeladonCity_DepartmentStore_3F_Text_SuperNES_4, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_Poster, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster_2::
	msgbox CeladonCity_DepartmentStore_3F_Text_Poster_2, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_CounterTutor:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeladonCity_DepartmentStore_3F_Text_GBAKid1:
	.string "Captured POKéMON are registered\nwith an ID No. and the OT.\pOT stands for “Original TRAINER” -\nthe TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_GBAKid3:
	.string "Come on, HAUNTER!\pI love HAUNTER!\nI collect them!\pHuh?\pHAUNTER turned into a different\nPOKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_GBAKid2:
	.string "All right!\pMy buddy's going to trade me his\nKANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_LittleGirl:
	.string "You can identify POKéMON you get\nin trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_FloorSign:
	.string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_TV1:
	.string "An RPG!\nThere's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_TV2:
	.string "A sports game!\nDad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_TV3:
	.string "A puzzle game!\nLooks addictive!$"

CeladonCity_DepartmentStore_3F_Text_TV4:
	.string "A fighting game!\nLooks tough!$"

CeladonCity_DepartmentStore_3F_Text_SuperNES:
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_SuperNES_2:
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_SuperNES_3:
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_SuperNES_4:
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_Poster:
	.string "Red and Green!\nBoth are POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_Poster_2:
	.string "Red and Green!\nBoth are POKéMON!$"
