PewterCity_House1_MapScripts::
	.byte 0

PewterCity_House1_EventScript_BaldingMan::
	msgbox PewterCity_House1_Text_BaldingMan, MSGBOX_NPC
	end

PewterCity_House1_EventScript_LittleBoy::
	msgbox PewterCity_House1_Text_LittleBoy, MSGBOX_NPC
	end

PewterCity_House1_Text_BaldingMan:
	.string "Our POKéMON's an outsider, so it's\nfinicky and hard to handle.\pAn outsider is a POKéMON that you\nget in a trade.\pIt grows fast, but it may ignore an\nunskilled TRAINER in battle.\pIf only we had some BADGES…$"

PewterCity_House1_Text_LittleBoy:
	.string "NIDORAN, sit!$"
