EcruteakPokecenter1F_MapScripts::
	.byte 0

EcruteakPokecenter1F_EventScript_Nurse::
	msgbox EcruteakPokecenter1F_Text_Nurse, MSGBOX_NPC
	end

EcruteakPokecenter1F_EventScript_PokefanM::
	msgbox EcruteakPokecenter1F_Text_PokefanM, MSGBOX_NPC
	end

EcruteakPokecenter1F_EventScript_CooltrainerF::
	msgbox EcruteakPokecenter1F_Text_CooltrainerF, MSGBOX_NPC
	end

EcruteakPokecenter1F_EventScript_GymGuide::
	msgbox EcruteakPokecenter1F_Text_GymGuide, MSGBOX_NPC
	end

EcruteakPokecenter1F_Text_Nurse:
	.string "They say the HOENN champion's\njourney is just getting started.\lWonder where they'll go next.$"

EcruteakPokecenter1F_Text_PokefanM:
	.string "This route sure gets more foot\ntraffic now that HOENN trainers\lkeep showing up.$"

EcruteakPokecenter1F_Text_CooltrainerF:
	.string "MORTY, the GYM\nLEADER, is soooo\lcool.\pHis POKéMON are\nreally tough too.$"

EcruteakPokecenter1F_Text_GymGuide:
	.string "LAKE OF RAGE…\pThe appearance of\na GYARADOS swarm…\pI smell a conspir-\nacy. I know it!$"
