OlivineCity_MapScripts::
	.byte 0

OlivineCity_EventScript_Sailor1::
	msgbox OlivineCity_Text_Sailor1, MSGBOX_NPC
	end

OlivineCity_EventScript_StandingYoungster::
	msgbox OlivineCity_Text_StandingYoungster, MSGBOX_NPC
	end

OlivineCity_EventScript_Sailor2::
	msgbox OlivineCity_Text_Sailor2, MSGBOX_NPC
	end

OlivineCity_EventScript_Sign::
	msgbox OlivineCity_Text_Sign, MSGBOX_SIGN
	end

OlivineCity_EventScript_PortSign::
	msgbox OlivineCity_Text_PortSign, MSGBOX_SIGN
	end

OlivineCity_EventScript_OlivineGymSign::
	msgbox OlivineCity_Text_OlivineGymSign, MSGBOX_SIGN
	end

OlivineCity_EventScript_OlivineLighthouseSign::
	msgbox OlivineCity_Text_OlivineLighthouseSign, MSGBOX_SIGN
	end

OlivineCity_EventScript_BattleTowerSign::
	msgbox OlivineCity_Text_BattleTowerSign, MSGBOX_SIGN
	end

OlivineCity_Text_Sailor1:
	.string "Dark roads are\ndangerous at\lnight.\pBut in the pitch-\nblack of night,\pthe sea is even\nmore treacherous!\pWithout the beacon\nof the LIGHTHOUSE\pto guide it, no\nship can sail.$"

OlivineCity_Text_StandingYoungster:
	.string "Did you hear? A HOENN trainer\nbecame Champion, and now folks\lhere want to challenge them.$"

OlivineCity_Text_Sailor2:
	.string "The sea is sweet!\pSunsets on the sea\nare marvelous!\pSing with me! \nYo-ho! Blow the\lman down!…$"

OlivineCity_Text_Sign:
	.string "OLIVINE CITY\pThe Port Closest\nto Foreign Lands$"

OlivineCity_Text_PortSign:
	.string "OLIVINE PORT\nFAST SHIP PIER$"

OlivineCity_Text_OlivineGymSign:
	.string "OLIVINE CITY\nPOKéMON GYM\lLEADER: JASMINE\pThe Steel-Clad\nDefense Girl$"

OlivineCity_Text_OlivineLighthouseSign:
	.string "OLIVINE LIGHTHOUSE\nAlso known as the\lGLITTER LIGHTHOUSE$"

OlivineCity_Text_BattleTowerSign:
	.string "BATTLE TOWER AHEAD\nOpening Now!$"
