ViridianCity_MapScripts::
	.byte 0

ViridianCity_EventScript_DreamEaterTutor::
	msgbox ViridianCity_Text_DreamEaterTutor, MSGBOX_NPC
	end

ViridianCity_EventScript_OldMan::
	msgbox ViridianCity_Text_OldMan, MSGBOX_NPC
	end

ViridianCity_EventScript_TutorialOldMan::
	msgbox ViridianCity_Text_TutorialOldMan, MSGBOX_NPC
	end

ViridianCity_EventScript_Woman::
	msgbox ViridianCity_Text_Woman, MSGBOX_NPC
	end

ViridianCity_EventScript_Youngster::
	msgbox ViridianCity_Text_Youngster, MSGBOX_NPC
	end

ViridianCity_EventScript_Boy::
	msgbox ViridianCity_Text_Boy, MSGBOX_NPC
	end

ViridianCity_EventScript_TrainerTips1::
	msgbox ViridianCity_Text_TrainerTips1, MSGBOX_SIGN
	end

ViridianCity_EventScript_GymSign::
	msgbox ViridianCity_Text_GymSign, MSGBOX_SIGN
	end

ViridianCity_EventScript_TrainerTips2::
	msgbox ViridianCity_Text_TrainerTips2, MSGBOX_SIGN
	end

ViridianCity_EventScript_CitySign::
	msgbox ViridianCity_Text_CitySign, MSGBOX_SIGN
	end

ViridianCity_EventScript_GymDoor::
	msgbox ViridianCity_Text_GymDoor, MSGBOX_SIGN
	end

ViridianCity_Text_DreamEaterTutor:
	.string "I never put much stock in rumors,\nbut two Leagues cleared is two\lLeagues cleared. Impressive.$"

ViridianCity_Text_OldMan:
	.string "I've fished this stretch of KANTO\nfor years. Lately it's all anyone\ltalks about -- some far-off champion.$"

ViridianCity_Text_TutorialOldMan:
	.string "I've fished this stretch of KANTO\nfor years. Lately it's all anyone\ltalks about -- some far-off champion.$"

ViridianCity_Text_Woman:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

ViridianCity_Text_Youngster:
	.string "Folks in KANTO don't get many\nvisitors from HOENN. Word is one\lof them cleaned up in JOHTO too.$"

ViridianCity_Text_Boy:
	.string "Those POKé BALLS at your waist!\nYou have POKéMON, don't you?\pIt's great that you can carry and\nuse POKéMON anytime, anywhere.$"

ViridianCity_Text_TrainerTips1:
	.string "TRAINER TIPS\pCatch POKéMON and expand your\ncollection.\pThe more you have, the easier it\nis to battle.$"

ViridianCity_Text_GymSign:
	.string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_TrainerTips2:
	.string "TRAINER TIPS\pThe battle moves of POKéMON are\nlimited by their POWER POINTS, PP.\pTo replenish PP, rest your tired\nPOKéMON at a POKéMON CENTER.$"

ViridianCity_Text_CitySign:
	.string "VIRIDIAN CITY \nThe Eternally Green Paradise$"

ViridianCity_Text_GymDoor:
	.string "VIRIDIAN GYM's doors are locked…$"
