CeladonCity_MapScripts::
	.byte 0

CeladonCity_EventScript_FatMan::
	msgbox CeladonCity_Text_FatMan, MSGBOX_NPC
	end

CeladonCity_EventScript_LittleGirl::
	msgbox CeladonCity_Text_LittleGirl, MSGBOX_NPC
	end

CeladonCity_EventScript_Woman::
	msgbox CeladonCity_Text_Woman, MSGBOX_NPC
	end

CeladonCity_EventScript_OldMan2::
	msgbox CeladonCity_Text_OldMan2, MSGBOX_NPC
	end

CeladonCity_EventScript_SoftboiledTutor::
	msgbox CeladonCity_Text_SoftboiledTutor, MSGBOX_NPC
	end

CeladonCity_EventScript_OldMan1::
	msgbox CeladonCity_Text_OldMan1, MSGBOX_NPC
	end

CeladonCity_EventScript_Boy::
	msgbox CeladonCity_Text_Boy, MSGBOX_NPC
	end

CeladonCity_EventScript_SilphCoScientist::
	msgbox CeladonCity_Text_SilphCoScientist, MSGBOX_NPC
	end

CeladonCity_EventScript_TrainerTips2::
	msgbox CeladonCity_Text_TrainerTips2, MSGBOX_SIGN
	end

CeladonCity_EventScript_PrizeExchangeSign::
	msgbox CeladonCity_Text_PrizeExchangeSign, MSGBOX_SIGN
	end

CeladonCity_EventScript_GameCornerSign::
	msgbox CeladonCity_Text_GameCornerSign, MSGBOX_SIGN
	end

CeladonCity_EventScript_CitySign::
	msgbox CeladonCity_Text_CitySign, MSGBOX_SIGN
	end

CeladonCity_EventScript_MansionSign::
	msgbox CeladonCity_Text_MansionSign, MSGBOX_SIGN
	end

CeladonCity_EventScript_TrainerTips1::
	msgbox CeladonCity_Text_TrainerTips1, MSGBOX_SIGN
	end

CeladonCity_EventScript_DeptStoreSign::
	msgbox CeladonCity_Text_DeptStoreSign, MSGBOX_SIGN
	end

CeladonCity_EventScript_GymSign::
	msgbox CeladonCity_Text_GymSign, MSGBOX_SIGN
	end

CeladonCity_Text_FatMan:
	.string "KANTO's got its own trainers worth\nwatching, but even we're curious\labout this HOENN-JOHTO champion.$"

CeladonCity_Text_LittleGirl:
	.string "I got my KOFFING in CINNABAR.\pIt's usually nice, but it breathes\npoison when it's angry.$"

CeladonCity_Text_Woman:
	.string "CELADON takes pride in its efforts\nto keep the city beautiful.\pThat's why the new GAME CORNER is\nbad for our city's image.$"

CeladonCity_Text_OldMan2:
	.string "Moan…\nI blew it all at the slots!\pI knew I should have cashed in my\nCOINS for prizes!$"

CeladonCity_Text_SoftboiledTutor:
	.string "They say a trainer beat both the\nHOENN and JOHTO Leagues. Wonder\lif they'll try KANTO next.$"

CeladonCity_Text_OldMan1:
	.string "KANTO's peaceful most days, but\neven here we've heard the stories\labout that HOENN trainer.$"

CeladonCity_Text_Boy:
	.string "Aaaagh, ow…\nI scalded my tongue!\pThis nice old lady in the MANSION\ngave me some TEA.\pBut it was boiling hot!\nGotta cool it to drink it.$"

CeladonCity_Text_SilphCoScientist:
	.string "Oh, what am I to do…\pSomeone stole our SILPH SCOPE.\pThe thief came running this way,\nI'm sure of it.\pBut I lost sight of him!\nWhere'd he go?$"

CeladonCity_Text_TrainerTips2:
	.string "TRAINER TIPS\pGUARD SPEC. protects POKéMON\nfrom status-reduction moves during\lbattle.\pGet your items at the\nCELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign:
	.string "COINS exchanged for prizes!\nPRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign:
	.string "ROCKET GAME CORNER\nThe playground for grown-ups!$"

CeladonCity_Text_CitySign:
	.string "CELADON CITY\nThe City of Rainbow Dreams$"

CeladonCity_Text_MansionSign:
	.string "CELADON MANSION$"

CeladonCity_Text_TrainerTips1:
	.string "TRAINER TIPS\pX ACCURACY boosts the accuracy of\ntechniques.\pDIRE HIT jacks up the likelihood\nof critical hits.\pGet your items at the CELADON\nDEPT. STORE!$"

CeladonCity_Text_DeptStoreSign:
	.string "Find what you need at the\nCELADON DEPT. STORE!$"

CeladonCity_Text_GymSign:
	.string "My grandkids keep going on about\nsome trainer from HOENN. Sounds\llike quite the journey so far.$"
