Route2_ViridianForest_SouthEntrance_MapScripts::
	.byte 0

Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
	msgbox Route2_ViridianForest_SouthEntrance_Text_Woman1, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
	msgbox Route2_ViridianForest_SouthEntrance_Text_Woman2, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_Woman1:
	.string "Are you going to VIRIDIAN FOREST?\nIt's a natural maze in there.\lBe careful you don't get lost.$"

Route2_ViridianForest_SouthEntrance_Text_Woman2:
	.string "RATTATA may be small, but don't\nunderestimate its wicked bite.\pHave you caught one already?$"
