SaffronCity_PokemonTrainerFanClub_MapScripts::
	.byte 0

SaffronCity_PokemonTrainerFanClub_EventScript_CrushGirl::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_CrushGirl, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_LittleGirl::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_LittleGirl, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_Youngster::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_Youngster, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_Gentleman::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_Gentleman, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_Woman::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_Woman, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_Rocker::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_Rocker, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_Beauty::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_Beauty, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_EventScript_BlackBelt::
	msgbox SaffronCity_PokemonTrainerFanClub_Text_BlackBelt, MSGBOX_NPC
	end

SaffronCity_PokemonTrainerFanClub_Text_CrushGirl:
	.string "SABRINA is my pick. She knew\nyou were coming. She didn't\lget up.$"

SaffronCity_PokemonTrainerFanClub_Text_LittleGirl:
	.string "Do you know what?\nI want to be like SABRINA!\pI want to be a psychic girl just\nlike her!$"

SaffronCity_PokemonTrainerFanClub_Text_Youngster:
	.string "BROCK's my hero!\nHe's a man among men!\pHeheh, I got my mom to do\nsomething for me.\pI got her to embroider “BROCK”\non my shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_Gentleman:
	.string "We're not taking new members.\nLeast of all famous ones.$"

SaffronCity_PokemonTrainerFanClub_Text_Woman:
	.string "KANTO's got its own trainers\nworth watching. Even we're\lcurious about the HOENN one.$"

SaffronCity_PokemonTrainerFanClub_Text_Rocker:
	.string "BLAINE is my man. Two Leagues?\nHe'd still make you answer\la riddle first.$"

SaffronCity_PokemonTrainerFanClub_Text_Beauty:
	.string "I follow ERIKA. She never once\nleft CELADON to be noticed.$"

SaffronCity_PokemonTrainerFanClub_Text_BlackBelt:
	.string "Hiyah! There is but one TRAINER\nwho has my respect.\pAnd that is none other than my\nMASTER at the FIGHTING DOJO.\pYou should become a fan of my\nMASTER like me! Hiyah!$"
