RuinsOfAlphHoOhItemRoom_MapScripts::
	.byte 0

RuinsOfAlphHoOhItemRoom_EventScript_AncientReplica::
	msgbox RuinsOfAlphHoOhItemRoom_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphHoOhItemRoom_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphHoOhItemRoom_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphHoOhItemRoom_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphHoOhItemRoom_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
