Route8_MapScripts::
	.byte 0

Route8_EventScript_Julia::
	trainerbattle_single TRAINER_KANTO_LASS_JULIA, Route8_Text_JuliaSeen, Route8_Text_JuliaBeaten
	msgbox Route8_Text_JuliaBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Rich::
	trainerbattle_single TRAINER_KANTO_GAMER_RICH, Route8_Text_RichSeen, Route8_Text_RichBeaten
	msgbox Route8_Text_RichBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Glenn::
	trainerbattle_single TRAINER_KANTO_SUPER_NERD_GLENN, Route8_Text_GlennSeen, Route8_Text_GlennBeaten
	msgbox Route8_Text_GlennBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Paige::
	trainerbattle_single TRAINER_KANTO_LASS_PAIGE, Route8_Text_PaigeSeen, Route8_Text_PaigeBeaten
	msgbox Route8_Text_PaigeBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Leslie::
	trainerbattle_single TRAINER_KANTO_SUPER_NERD_LESLIE, Route8_Text_LeslieSeen, Route8_Text_LeslieBeaten
	msgbox Route8_Text_LeslieBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Andrea::
	trainerbattle_single TRAINER_KANTO_LASS_ANDREA, Route8_Text_AndreaSeen, Route8_Text_AndreaBeaten
	msgbox Route8_Text_AndreaBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Megan::
	trainerbattle_single TRAINER_KANTO_LASS_MEGAN, Route8_Text_MeganSeen, Route8_Text_MeganBeaten
	msgbox Route8_Text_MeganBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Stan::
	trainerbattle_single TRAINER_KANTO_GAMER_STAN, Route8_Text_StanSeen, Route8_Text_StanBeaten
	msgbox Route8_Text_StanBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Aidan::
	trainerbattle_single TRAINER_KANTO_SUPER_NERD_AIDAN, Route8_Text_AidanSeen, Route8_Text_AidanBeaten
	msgbox Route8_Text_AidanBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Eli::
	trainerbattle_single TRAINER_KANTO_TWINS_ELI_ANNE, Route8_Text_EliSeen, Route8_Text_EliBeaten
	msgbox Route8_Text_EliBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Anne::
	trainerbattle_single TRAINER_KANTO_TWINS_ELI_ANNE_2, Route8_Text_AnneSeen, Route8_Text_AnneBeaten
	msgbox Route8_Text_AnneBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Ricardo::
	trainerbattle_single TRAINER_KANTO_BIKER_RICARDO, Route8_Text_RicardoSeen, Route8_Text_RicardoBeaten
	msgbox Route8_Text_RicardoBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_Jaren::
	trainerbattle_single TRAINER_KANTO_BIKER_JAREN, Route8_Text_JarenSeen, Route8_Text_JarenBeaten
	msgbox Route8_Text_JarenBeaten, MSGBOX_AUTOCLOSE
	end

Route8_EventScript_UndergroundPathSign::
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route8_Text_JuliaSeen:
	.string "…$"

Route8_Text_JuliaBeaten:
	.string "…$"

Route8_Text_RichSeen:
	.string "…$"

Route8_Text_RichBeaten:
	.string "…$"

Route8_Text_GlennSeen:
	.string "…$"

Route8_Text_GlennBeaten:
	.string "…$"

Route8_Text_PaigeSeen:
	.string "…$"

Route8_Text_PaigeBeaten:
	.string "…$"

Route8_Text_LeslieSeen:
	.string "…$"

Route8_Text_LeslieBeaten:
	.string "…$"

Route8_Text_AndreaSeen:
	.string "…$"

Route8_Text_AndreaBeaten:
	.string "…$"

Route8_Text_MeganSeen:
	.string "…$"

Route8_Text_MeganBeaten:
	.string "…$"

Route8_Text_StanSeen:
	.string "…$"

Route8_Text_StanBeaten:
	.string "…$"

Route8_Text_AidanSeen:
	.string "…$"

Route8_Text_AidanBeaten:
	.string "…$"

Route8_Text_EliSeen:
	.string "…$"

Route8_Text_EliBeaten:
	.string "…$"

Route8_Text_AnneSeen:
	.string "…$"

Route8_Text_AnneBeaten:
	.string "…$"

Route8_Text_RicardoSeen:
	.string "…$"

Route8_Text_RicardoBeaten:
	.string "…$"

Route8_Text_JarenSeen:
	.string "…$"

Route8_Text_JarenBeaten:
	.string "…$"

Route8_Text_UndergroundPathSign:
	.string "UNDERGROUND PATH\nCELADON CITY - LAVENDER TOWN$"
