RuinsOfAlphAerodactylChamber_MapScripts::
	.byte 0

RuinsOfAlphAerodactylChamber_EventScript_AncientReplica::
	msgbox RuinsOfAlphAerodactylChamber_Text_AncientReplica, MSGBOX_SIGN
	end

RuinsOfAlphAerodactylChamber_EventScript_AncientReplica_2::
	msgbox RuinsOfAlphAerodactylChamber_Text_AncientReplica_2, MSGBOX_SIGN
	end

RuinsOfAlphAerodactylChamber_Text_AncientReplica:
	.string "It's a replica of\nan ancient POKé-\lMON.$"

RuinsOfAlphAerodactylChamber_Text_AncientReplica_2:
	.string "It's a replica of\nan ancient POKé-\lMON.$"
